"""Step 0 of the simulator-paired one-step ETT (AntMaze V6): is the expert
advice a_b of the SAME pre-intervention context as the queried action and its
outcome reconstructable, and is one-step motion deterministic?  No training.

The ETT of the PointMaze pipeline fits F(s, a_b, a_q) -> s' plus an onset
head on same-context tuples.  For AntMaze the behaviour policy is the
privileged teacher (`rockfall_clock_v6_teacher.LongTwoRockfallTeacher`): a
deterministic latched relay (leg / trail / stall-nudge state) whose only use
of the hidden context is the prospective go / wait decision taken the first
time it stands at a hazard mouth, from the zone's timetable.  So a_b at a
context (s, t, hidden) is a function of (i) the route INTENT (the collector's
detour coin, an independent RNG stream -- never the realised route), (ii)
the position history up to t (leg, trail, nudges, step), (iii) the timetable
and the step at which each zone's rule was consulted.

What this script does, in order:

  hidden   Per d05 episode: intent, U1 / U2, t0_1 / t0_2, rock jitter.  Read
           from the per-seed sidecars where they exist (seeds 606 / 610 /
           611); for seeds 607-609 (sidecars not on any node) REGENERATED by
           replaying the collector's fixed-order RNG consumption (an env
           seeded with the collection seed, one reset per episode in order;
           the route coin from `seed + ROUTE_SEED_OFFSET`), and VALIDATED
           exactly against the three available sidecars first.
  diag     Every logged row: a fresh teacher (intent) driven along the logged
           observations with the original timetable must reproduce the
           logged torque exactly and the recorded per-step holding zone;
           the teacher state before every anchor row is snapshotted.
  branch   Every pilot anchor: the branch's redrawn hidden context (the same
           hazard seed the generator used) -> the teacher state at t
           reconstructed from the logged history, the zone latches
           RE-DERIVED under the new timetable at the recorded consultation
           steps -> a_b; compared with the queried torque a_q (the logged
           one): diagonal / off-diagonal (hold vs drive), by region and
           time.  Under the ORIGINAL timetable the same reconstruction must
           give a_b == a_q (checked).
  step     One-step determinism as a HYPOTHESIS: (i) restore (s_t, original
           hidden, t), execute the logged torque, compare with the logged
           s_{t+1}, rows outside rock bursts vs inside; (ii) the existing
           branches' first post-query row vs the logged s_{t+1} (same torque,
           different hidden), all anchors, split by burst activity.
  report   Markdown.

Missing information is reported, not patched: the d05 log contains no
failures (every episode reached the goal), so onset labels exist only in the
simulator branches; and anything the reconstruction cannot establish stops
the label construction.

  python scripts/audit_v6_ett_context.py hidden|diag|branch|step|report
"""
from __future__ import annotations

import argparse
import copy
import json
import os
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'scripts'))
os.environ.setdefault('JAX_PLATFORMS', 'cpu')

import exp_v6_mainline_pilot as MP  # noqa: E402

OUT = MP.OUT / 'ett_context'
DS = ROOT / 'artifacts' / 'rockfall_clock_v6' / 'dataset'
POOL_SIDECAR = DS / 'antmaze_rockfall_clock_v6_p050_plus5k_sidecar.npz'
SEED_SIDECAR = {606: DS / 'antmaze_rockfall_clock_v6_p050_sidecar.npz', 610: DS / 'antmaze_rockfall_clock_v6_p050_s610_sidecar.npz', 611: DS / 'antmaze_rockfall_clock_v6_p050_s611_sidecar.npz'}
N_PER_SEED = 1000
ROUTE_SEED_OFFSET = 370_003
ROCKFALL_STEPS = 72
TOL = 1e-5
STATE_DIM, OBS_W = MP.STATE_DIM, MP.OBS_W
STEP_SAMPLE = 3000
STEP_SEED = 181_000_000

TEACHER_FIELDS = ('_leg', '_trail', '_nudge_left', '_nudge_sign', '_nudges', '_step', '_route', '_decision', '_normal_decision',
                  '_override_zone', '_deliberate_override', '_release_step', '_hold_steps', '_holding_zone')


def snapshot(teacher):
  return {f: copy.deepcopy(getattr(teacher, f)) for f in TEACHER_FIELDS}


def restore_teacher(teacher, snap):
  for f, v in snap.items():
    setattr(teacher, f, copy.deepcopy(v))


def schedule_of(u, t0, t):
  return {'t': int(t), 'zones': {z: {'active': bool(u[z]), 'sampled_start': int(t0[z]), 'start': (int(t0[z]) if u[z] else None),
                                     'end': (int(t0[z]) + ROCKFALL_STEPS if u[z] else None)} for z in (1, 2)}}


def in_burst(u, t0, t):
  return {z: bool(u[z] and int(t0[z]) <= t < int(t0[z]) + ROCKFALL_STEPS) for z in (1, 2)}


def make_env_teacher(seed):
  import rockfall_clock_v6_teacher as CT
  from crl import envs as envs_mod
  cfg, teacher = CT.make_teacher(p_active_1=0.5, p_active_2=0.5)
  env = envs_mod.make_env(CT.ENV_NAME, cfg, seed=int(seed))
  return env, teacher


def obs58(env, row31):
  """The teacher's observation: the 29-dim state + the env's 29-dim goal template with the logged goal xy (as build_v6_branch_replay.restore sets it)."""
  full = np.array(env._goal_state_full, np.float32)
  full[:2] = row31[STATE_DIM:OBS_W]
  return np.concatenate([row31[:STATE_DIM].astype(np.float32), full])


# ------------------------------------------------------------------ hidden
def mode_hidden(args):
  OUT.mkdir(parents=True, exist_ok=True)
  import rockfall_clock_v6_teacher as CT
  from crl import envs as envs_mod
  with np.load(MP.SIDECAR, allow_pickle=True) as sc:
    src = sc['source_episode'].astype(np.int64)
  with np.load(POOL_SIDECAR, allow_pickle=True) as pk:
    seed_of = pk['source_seed'].astype(np.int64)[src]; ep_of = pk['source_episode'].astype(np.int64)[src]
  N = len(src)
  H = {'seed': seed_of, 'episode_in_seed': ep_of, 'intent_detour': np.zeros(N, bool), 'u1': np.zeros(N, bool), 'u2': np.zeros(N, bool),
       't0_1': np.zeros(N, np.int64), 't0_2': np.zeros(N, np.int64), 'jitter_1': np.zeros((N, 4, 2), np.float32), 'jitter_2': np.zeros((N, 4, 2), np.float32),
       'source': np.zeros(N, dtype='<U12'), 'route_realized_sidecar': np.zeros(N, dtype='<U8'), 'route_realized_d05': np.zeros(N, dtype='<U8'),
       'decision_1': np.zeros(N, dtype='<U4'), 'decision_2': np.zeros(N, dtype='<U4'), 'mouth_1': np.full(N, -1, np.int64), 'mouth_2': np.full(N, -1, np.int64)}
  with np.load(MP.SIDECAR, allow_pickle=True) as sc:
    H['route_realized_d05'][:] = sc['route_realized'].astype(str)
  # 1. regenerate the collector's draws for every seed (validated against the sidecars that exist)
  cfg, _ = CT.make_teacher(p_active_1=0.5, p_active_2=0.5)
  regen, validation = {}, {}
  for s in sorted(set(seed_of.tolist())):
    env = envs_mod.make_env(CT.ENV_NAME, cfg, seed=int(s))
    rng = np.random.default_rng(int(s) + ROUTE_SEED_OFFSET)
    R = {'intent_detour': np.zeros(N_PER_SEED, bool), 'u1': np.zeros(N_PER_SEED, bool), 'u2': np.zeros(N_PER_SEED, bool), 't0_1': np.zeros(N_PER_SEED, np.int64),
         't0_2': np.zeros(N_PER_SEED, np.int64), 'jitter_1': np.zeros((N_PER_SEED, 4, 2), np.float32), 'jitter_2': np.zeros((N_PER_SEED, 4, 2), np.float32)}
    for i in range(N_PER_SEED):
      R['intent_detour'][i] = bool(rng.random() < 0.05)                 # collect_rockfall_clock_v6_dataset: one draw per episode, in order
      env.reset()
      R['u1'][i], R['u2'][i] = bool(env.privileged_rockfall_active_1), bool(env.privileged_rockfall_active_2)
      R['t0_1'][i], R['t0_2'][i] = int(env.privileged_sampled_start(1)), int(env.privileged_sampled_start(2))
      R['jitter_1'][i], R['jitter_2'][i] = np.asarray(env._drop_jitter[1], np.float32), np.asarray(env._drop_jitter[2], np.float32)
    regen[s] = R
    if s in SEED_SIDECAR:
      with np.load(SEED_SIDECAR[s], allow_pickle=True) as sc:
        assert np.array_equal(sc['episode_id'], np.arange(N_PER_SEED)) and np.array_equal(sc['reset_index'], np.arange(N_PER_SEED))
        v = {'intent_detour': int((sc['teacher_take_detour'] == R['intent_detour']).sum()), 'u1': int((sc['u1'] == R['u1']).sum()), 'u2': int((sc['u2'] == R['u2']).sum()),
             't0_1': int((sc['t0_1'] == R['t0_1']).sum()), 't0_2': int((sc['t0_2'] == R['t0_2']).sum()),
             'jitter_1_maxdiff': float(np.abs(sc['rock_jitter_zone_1'].astype(np.float32) - R['jitter_1']).max()),
             'jitter_2_maxdiff': float(np.abs(sc['rock_jitter_zone_2'].astype(np.float32) - R['jitter_2']).max()),
             'route_intent_eq_realized': int((sc['route'] == sc['route_realized']).sum()), 'n': N_PER_SEED}
      validation[str(s)] = v
      print(f'seed {s}: regeneration vs sidecar {v}', flush=True)
  ok = all(v['intent_detour'] == v['u1'] == v['u2'] == v['t0_1'] == v['t0_2'] == N_PER_SEED and v['jitter_1_maxdiff'] == 0.0 and v['jitter_2_maxdiff'] == 0.0 for v in validation.values())
  # 2. fill the d05 table
  for i in range(N):
    s, e = int(seed_of[i]), int(ep_of[i])
    if s in SEED_SIDECAR:
      with np.load(SEED_SIDECAR[s], allow_pickle=True) as sc:
        H['intent_detour'][i] = bool(sc['teacher_take_detour'][e]); H['u1'][i], H['u2'][i] = bool(sc['u1'][e]), bool(sc['u2'][e])
        H['t0_1'][i], H['t0_2'][i] = int(sc['t0_1'][e]), int(sc['t0_2'][e]); H['jitter_1'][i], H['jitter_2'][i] = sc['rock_jitter_zone_1'][e], sc['rock_jitter_zone_2'][e]
        H['route_realized_sidecar'][i] = str(sc['route_realized'][e]); H['decision_1'][i], H['decision_2'][i] = str(sc['decision_zone_1'][e]), str(sc['decision_zone_2'][e])
        H['mouth_1'][i], H['mouth_2'][i] = int(sc['mouth_step_zone_1'][e]), int(sc['mouth_step_zone_2'][e])
      H['source'][i] = 'sidecar'
    else:
      R = regen[s]
      H['intent_detour'][i] = R['intent_detour'][e]; H['u1'][i], H['u2'][i] = R['u1'][e], R['u2'][e]; H['t0_1'][i], H['t0_2'][i] = R['t0_1'][e], R['t0_2'][e]
      H['jitter_1'][i], H['jitter_2'][i] = R['jitter_1'][e], R['jitter_2'][e]; H['source'][i] = 'regenerated'
  intent = np.where(H['intent_detour'], 'detour', 'shortcut')
  summ = {'n': N, 'per_seed': {str(s): int((seed_of == s).sum()) for s in sorted(set(seed_of.tolist()))}, 'regeneration_validation': validation, 'regeneration_exact_on_available_seeds': bool(ok),
          'source_counts': {k: int((H['source'] == k).sum()) for k in ('sidecar', 'regenerated')},
          'intent_vs_realized_d05': {'equal': int((intent == H['route_realized_d05']).sum()), 'detour_intent': int(H['intent_detour'].sum()), 'detour_realized': int((H['route_realized_d05'] == 'detour').sum())},
          'template_goal_note': 'obs58 = state29 + env goal template with the logged goal xy (build_v6_branch_replay.restore convention)'}
  np.savez_compressed(OUT / 'hidden.npz', **H, intent=intent)
  MP.write_json(OUT / 'hidden.json', summ)
  print(json.dumps(summ, indent=1), flush=True)


# -------------------------------------------------------------------- diag
def replay_episode(env, teacher, obs, L, intent, u, t0, holding_ref=None, anchor_ts=()):
  """Drive a fresh teacher along the logged rows of one episode under the original timetable.  Returns per-row torques, the
  decision steps, and the teacher snapshots BEFORE acting at the requested anchor rows."""
  teacher.fresh(route=intent)
  A = np.zeros((L - 1, 8), np.float32); hold = np.full(L - 1, -1, np.int8); dstep = {1: -1, 2: -1}
  snaps = {}
  want = set(int(t) for t in anchor_ts)
  for t in range(L - 1):
    if t in want:
      snaps[t] = snapshot(teacher)
    before = dict(teacher._decision)
    A[t] = teacher.act(obs58(env, obs[t]), schedule_of(u, t0, t))
    for z in (1, 2):
      if before[z] is None and teacher._decision[z] is not None:
        dstep[z] = t
    hold[t] = -1 if teacher._holding_zone is None else int(teacher._holding_zone)
  return A, hold, dstep, snaps


def mode_diag(args):
  H = dict(np.load(OUT / 'hidden.npz', allow_pickle=False))
  obs, act, lengths, _ = MP.load_dataset()
  anchors, _ = MP.AnchorSet.load(MP.OUT / 'anchors.npz')
  env, teacher = make_env_teacher(191_000_000)
  env.reset()
  N = len(lengths)
  per_ep, rows_total, rows_exact, rows_tol, maxdiff_all = [], 0, 0, 0, 0.0
  hold_checked = hold_agree = 0
  dsteps = np.full((N, 2), -1, np.int64)
  snap_store = {}
  t0_ = time.time()
  for e in range(N):
    L = int(lengths[e]); u = {1: bool(H['u1'][e]), 2: bool(H['u2'][e])}; t0 = {1: int(H['t0_1'][e]), 2: int(H['t0_2'][e])}
    ts = anchors.t[anchors.episode == e]
    A, hold, dstep, snaps = replay_episode(env, teacher, obs[e], L, str(H['intent'][e]), u, t0, anchor_ts=ts)
    for t, sn in snaps.items():
      snap_store[(e, int(t))] = sn
    d = np.abs(A - act[e, :L - 1].astype(np.float32)).max(axis=1)
    rows_total += L - 1; rows_exact += int((d == 0).sum()); rows_tol += int((d <= TOL).sum()); maxdiff_all = max(maxdiff_all, float(d.max()))
    dsteps[e] = [dstep[1], dstep[2]]
    rec = {'episode': e, 'seed': int(H['seed'][e]), 'source': str(H['source'][e]), 'intent': str(H['intent'][e]), 'rows': L - 1, 'exact': int((d == 0).sum()), 'within_tol': int((d <= TOL).sum()),
           'maxdiff': float(d.max()), 'first_mismatch_row': (int(np.argmax(d > TOL)) if (d > TOL).any() else -1), 'decision_step_1': dstep[1], 'decision_step_2': dstep[2],
           'holds': int((hold >= 0).sum())}
    if H['source'][e] == 'sidecar':
      rec['sidecar_mouth'] = [int(H['mouth_1'][e]), int(H['mouth_2'][e])]; rec['sidecar_decision'] = [str(H['decision_1'][e]), str(H['decision_2'][e])]
      rec['replay_decision'] = [teacher._decision[1] or 'none', teacher._decision[2] or 'none']
      rec['decision_agree'] = bool(rec['sidecar_decision'] == rec['replay_decision'])
    per_ep.append(rec)
    if e % 100 == 0:
      print(f'episode {e}: rows {L - 1} exact {rec["exact"]} maxdiff {rec["maxdiff"]:.2e} decisions {dstep} ({time.time() - t0_:.0f} s)', flush=True)
  # holding-zone agreement for sidecar episodes (per-step recorded holding zone)
  hold_rows = []
  for s, p in SEED_SIDECAR.items():
    with np.load(p, allow_pickle=True) as sc:
      shz = sc['step_holding_zone']
    for e in np.flatnonzero(H['seed'] == s):
      L = int(lengths[e]); u = {1: bool(H['u1'][e]), 2: bool(H['u2'][e])}; t0 = {1: int(H['t0_1'][e]), 2: int(H['t0_2'][e])}
      _, hold, _, _ = replay_episode(env, teacher, obs[e], L, str(H['intent'][e]), u, t0)
      ref = shz[int(H['episode_in_seed'][e]), :L - 1].astype(np.int8)
      hold_checked += L - 1; hold_agree += int((hold == ref).sum())
      hold_rows.append({'episode': int(e), 'agree': int((hold == ref).sum()), 'rows': L - 1})
  # save the anchor snapshots (small fields only)
  keys = sorted(snap_store)
  S = {'episode': np.array([k[0] for k in keys], np.int64), 't': np.array([k[1] for k in keys], np.int64)}
  S['leg'] = np.array([snap_store[k]['_leg'] for k in keys], np.int64); S['step'] = np.array([snap_store[k]['_step'] for k in keys], np.int64)
  S['nudge_left'] = np.array([snap_store[k]['_nudge_left'] for k in keys], np.int64); S['nudge_sign'] = np.array([snap_store[k]['_nudge_sign'] for k in keys], np.float64)
  S['nudges'] = np.array([snap_store[k]['_nudges'] for k in keys], np.int64)
  S['decision'] = np.array([[{None: 0, 'go': 1, 'wait': 2}[snap_store[k]['_decision'][z]] for z in (1, 2)] for k in keys], np.int8)
  S['release'] = np.array([[(-1 if snap_store[k]['_release_step'][z] is None else snap_store[k]['_release_step'][z]) for z in (1, 2)] for k in keys], np.int64)
  S['holding'] = np.array([(-1 if snap_store[k]['_holding_zone'] is None else snap_store[k]['_holding_zone']) for k in keys], np.int8)
  S['hold_steps'] = np.array([[snap_store[k]['_hold_steps'][z] for z in (1, 2)] for k in keys], np.int64)
  trail = np.full((len(keys), 41, 2), np.nan, np.float32)
  for i, k in enumerate(keys):
    tr = snap_store[k]['_trail'][-41:]
    if tr:
      trail[i, -len(tr):] = np.asarray(tr, np.float32)
  S['trail_tail'] = trail; S['trail_len'] = np.array([len(snap_store[k]['_trail']) for k in keys], np.int64)
  S['decision_step'] = dsteps[S['episode']]
  np.savez_compressed(OUT / 'teacher_state_at_anchors.npz', **S)
  summ = {'rows': rows_total, 'exact': rows_exact, 'within_tol': rows_tol, 'maxdiff': maxdiff_all, 'episodes_all_exact': int(sum(r['exact'] == r['rows'] for r in per_ep)),
          'episodes_all_within_tol': int(sum(r['within_tol'] == r['rows'] for r in per_ep)), 'n_episodes': N,
          'holding_zone_rows_checked (sidecar seeds)': hold_checked, 'holding_zone_rows_agree': hold_agree,
          'decision_agree_sidecar': {'agree': int(sum(1 for r in per_ep if r.get('decision_agree'))), 'n': int(sum(1 for r in per_ep if 'decision_agree' in r))},
          'anchors_snapshotted': len(keys), 'wall_seconds': time.time() - t0_}
  MP.write_json(OUT / 'diag.json', {'summary': summ, 'per_episode': per_ep, 'holding_rows': hold_rows})
  print(json.dumps(summ, indent=1), flush=True)


# ------------------------------------------------------------------ branch
def rederive_latches(snap, u_new, t0_new, dstep):
  """The zone latches under a NEW timetable: every zone whose rule the teacher had consulted (at the recorded step) is re-decided by the
  same rule at that step under the new schedule; unconsulted zones stay None (the rule fires when the mouth is reached)."""
  import rockfall_clock_v6_teacher as CT
  snap = copy.deepcopy(snap)
  for z in (1, 2):
    if snap['_decision'][z] is None:
      continue
    m = int(dstep[z]); assert m >= 0
    if not u_new[z]:
      normal = 'go'
    else:
      cross_end = m + CT.CROSSING_STEPS[z] + CT.SAFETY_MARGIN
      normal = 'wait' if CT.intervals_overlap(int(t0_new[z]), int(t0_new[z]) + ROCKFALL_STEPS, m, cross_end) else 'go'
    snap['_normal_decision'][z] = normal; snap['_decision'][z] = normal
    snap['_release_step'][z] = (int(t0_new[z]) + ROCKFALL_STEPS + CT.RELEASE_MARGIN) if normal == 'wait' else None
  return snap


def mode_branch(args):
  import diag_v6_first_step_crossover as DG
  from exp_v6_learned_ett import REGIONS, region_of
  H = dict(np.load(OUT / 'hidden.npz', allow_pickle=False))
  obs, act, lengths, _ = MP.load_dataset()
  anchors, _ = MP.AnchorSet.load(MP.OUT / 'anchors.npz')
  with np.load(MP.OUT / 'branches_cf.npz', allow_pickle=False) as d:
    hz, bu1, bu2, boc = d['hazard_seed'], d['u1'], d['u2'], d['outcome'].astype(str)
  env, teacher = make_env_teacher(192_000_000)
  env.reset()
  K = anchors.n
  # hidden' per anchor: the generator's reseed + reset
  U1n, U2n, T1n, T2n = np.zeros(K, bool), np.zeros(K, bool), np.zeros(K, np.int64), np.zeros(K, np.int64)
  J1n, J2n = np.zeros((K, 4, 2), np.float32), np.zeros((K, 4, 2), np.float32)
  t0_ = time.time()
  for k in range(K):
    DG.reseed(env, int(hz[k])); env.reset()
    U1n[k], U2n[k] = bool(env.privileged_rockfall_active_1), bool(env.privileged_rockfall_active_2)
    T1n[k], T2n[k] = int(env.privileged_sampled_start(1)), int(env.privileged_sampled_start(2))
    J1n[k], J2n[k] = np.asarray(env._drop_jitter[1], np.float32), np.asarray(env._drop_jitter[2], np.float32)
  assert np.array_equal(U1n, bu1) and np.array_equal(U2n, bu2), 'the reseeded hidden draws differ from the branch file'
  print(f'hidden draws of {K} branches regenerated and matched (u1 / u2) in {time.time() - t0_:.0f} s', flush=True)
  # teacher state at every anchor: replay each episode once
  A_b = np.zeros((K, 8), np.float32); A_b_orig = np.zeros((K, 8), np.float32); hold_new = np.zeros(K, bool); hold_orig = np.zeros(K, bool)
  dec_new = np.zeros((K, 2), np.int8); dec_orig = np.zeros((K, 2), np.int8)
  by_ep = {}
  for k in range(K):
    by_ep.setdefault(int(anchors.episode[k]), []).append(k)
  t0_ = time.time()
  for n_done, (e, ks) in enumerate(sorted(by_ep.items())):
    L = int(lengths[e]); u = {1: bool(H['u1'][e]), 2: bool(H['u2'][e])}; t0 = {1: int(H['t0_1'][e]), 2: int(H['t0_2'][e])}
    ts = [int(anchors.t[k]) for k in ks]
    _, _, dstep, snaps = replay_episode(env, teacher, obs[e], L, str(H['intent'][e]), u, t0, anchor_ts=ts)
    for k in ks:
      t = int(anchors.t[k]); o = obs58(env, obs[e, t])
      restore_teacher(teacher, snaps[t]); A_b_orig[k] = teacher.act(o, schedule_of(u, t0, t)); hold_orig[k] = teacher._holding_zone is not None
      dec_orig[k] = [{None: 0, 'go': 1, 'wait': 2}[snaps[t]['_decision'][z]] for z in (1, 2)]
      un = {1: bool(U1n[k]), 2: bool(U2n[k])}; tn = {1: int(T1n[k]), 2: int(T2n[k])}
      sn = rederive_latches(snaps[t], un, tn, dstep)
      restore_teacher(teacher, sn); A_b[k] = teacher.act(o, schedule_of(un, tn, t)); hold_new[k] = teacher._holding_zone is not None
      dec_new[k] = [{None: 0, 'go': 1, 'wait': 2}[sn['_decision'][z]] for z in (1, 2)]
    if n_done % 100 == 0:
      print(f'{n_done} episodes ({time.time() - t0_:.0f} s)', flush=True)
  a_q = anchors.action.astype(np.float32)
  d_orig = np.abs(A_b_orig - a_q).max(axis=1); d_new = np.abs(A_b - a_q).max(axis=1)
  q_zero = np.abs(a_q).max(axis=1) == 0; b_zero = np.abs(A_b).max(axis=1) == 0
  cls = np.where(d_new <= TOL, 'diagonal', np.where(b_zero & ~q_zero, 'off_hold', np.where(~b_zero & q_zero, 'off_release', 'off_other')))
  reg = region_of(anchors.state[:, :2]); W = anchors.weight
  strata = {'all': np.ones(K, bool), 'reset rows (t = 0)': anchors.t == 0}
  for r, name in enumerate(REGIONS):
    if (reg == r).sum() >= 50:
      strata[f'anchor in {name}'] = reg == r
  summ = {'n': K, 'original_timetable_reconstruction_exact': int((d_orig == 0).sum()), 'original_within_tol': int((d_orig <= TOL).sum()), 'original_maxdiff': float(d_orig.max()),
          'classes': {c: int((cls == c).sum()) for c in ('diagonal', 'off_hold', 'off_release', 'off_other')},
          'classes_weighted': {c: float(W[cls == c].sum()) for c in ('diagonal', 'off_hold', 'off_release', 'off_other')},
          'off_other_maxdiff_median': float(np.median(d_new[cls == 'off_other'])) if (cls == 'off_other').any() else None,
          'by_stratum': {name: {'n': int(m.sum()), 'weight': float(W[m].sum()), **{c: float(W[m & (cls == c)].sum() / max(W[m].sum(), 1e-12)) for c in ('diagonal', 'off_hold', 'off_release', 'off_other')},
                                'holding_new': float(W[m & hold_new].sum() / max(W[m].sum(), 1e-12)), 'holding_orig': float(W[m & hold_orig].sum() / max(W[m].sum(), 1e-12)),
                                'death_share_branch': float(W[m & (boc == 'death')].sum() / max(W[m].sum(), 1e-12))}
                         for name, m in strata.items()},
          'death_by_class': {c: {'n': int((cls == c).sum()), 'death_share': float((boc[cls == c] == 'death').mean()) if (cls == c).any() else None} for c in ('diagonal', 'off_hold', 'off_release', 'off_other')},
          'onset_labels': {'branches_death': int((boc == 'death').sum()), 'branches_total': K, 'logged_failures_in_d05': 0}}
  np.savez_compressed(OUT / 'branch_advice.npz', a_b=A_b, a_b_orig=A_b_orig, a_q=a_q, cls=cls, hold_new=hold_new, hold_orig=hold_orig, dec_new=dec_new, dec_orig=dec_orig,
                      u1_new=U1n, u2_new=U2n, t0_1_new=T1n, t0_2_new=T2n, jitter_1_new=J1n, jitter_2_new=J2n, episode=anchors.episode, t=anchors.t)
  MP.write_json(OUT / 'branch.json', summ)
  print(json.dumps(summ, indent=1), flush=True)


# -------------------------------------------------------------------- step
def mode_step(args):
  import build_v6_branch_replay as B
  H = dict(np.load(OUT / 'hidden.npz', allow_pickle=False))
  obs, act, lengths, _ = MP.load_dataset()
  anchors, _ = MP.AnchorSet.load(MP.OUT / 'anchors.npz')
  env, _ = make_env_teacher(193_000_000)
  # (i) logged one-step replay under the original hidden context
  rng = np.random.default_rng(STEP_SEED)
  eps = rng.integers(0, len(lengths), size=STEP_SAMPLE)
  rows = []
  for e in eps:
    L = int(lengths[e]); t = int(rng.integers(0, L - 1))
    u = {1: bool(H['u1'][e]), 2: bool(H['u2'][e])}; t0 = {1: int(H['t0_1'][e]), 2: int(H['t0_2'][e])}
    env.reset(rockfall_active_1=u[1], rockfall_active_2=u[2], rockfall_start_1=t0[1], rockfall_start_2=t0[2])
    env._drop_jitter = {1: np.array(H['jitter_1'][e], np.float64), 2: np.array(H['jitter_2'][e], np.float64)}
    o = B.restore(env, obs[e, t, :STATE_DIM].astype(np.float64), obs[e, t, STATE_DIM:OBS_W].astype(np.float64), t)
    env._active, env._t0 = u, t0                      # restore() resets (fresh draws); put the original context back
    env._drop_jitter = {1: np.array(H['jitter_1'][e], np.float64), 2: np.array(H['jitter_2'][e], np.float64)}
    rmd = float(np.abs(o[:OBS_W] - obs[e, t]).max())
    o2, r, done, info = env.step(act[e, t].astype(np.float32))
    d = np.abs(o2[:STATE_DIM] - obs[e, t + 1, :STATE_DIM])
    burst = in_burst(u, t0, t) ; burst_next = in_burst(u, t0, t + 1)
    rows.append({'episode': int(e), 't': t, 'restore_maxdiff': rmd, 'step_maxdiff': float(d.max()), 'step_xy_diff': float(np.linalg.norm(d[:2])),
                 'burst_any': bool(any(burst.values()) or any(burst_next.values())), 'done': bool(done), 'reward': float(r)})
  sd = np.array([r['step_maxdiff'] for r in rows]); bz = np.array([r['burst_any'] for r in rows])
  q = lambda v: {'n': int(len(v)), 'median': float(np.median(v)) if len(v) else None, 'p90': float(np.percentile(v, 90)) if len(v) else None, 'p99': float(np.percentile(v, 99)) if len(v) else None, 'max': float(v.max()) if len(v) else None}
  res_i = {'restore_maxdiff': q(np.array([r['restore_maxdiff'] for r in rows])), 'step_maxdiff_all': q(sd), 'step_maxdiff_outside_bursts': q(sd[~bz]), 'step_maxdiff_inside_bursts': q(sd[bz]),
           'rows_exact_1e-5_outside_bursts': int((sd[~bz] <= 1e-5).sum()), 'rows_exact_1e-5_inside_bursts': int((sd[bz] <= 1e-5).sum())}
  # (ii) the branches' first post-query row vs the logged s_{t+1} (same torque, different hidden)
  with np.load(MP.OUT / 'branches_cf.npz', allow_pickle=False) as d:
    off, ep, tt = d['offset'], d['episode'], d['t']
    first = d['obs_rows'][off + 1, :STATE_DIM]
  logged_next = obs[ep, tt + 1, :STATE_DIM]
  dd = np.abs(first - logged_next).max(axis=1)
  A = dict(np.load(OUT / 'branch_advice.npz', allow_pickle=False)) if (OUT / 'branch_advice.npz').exists() else None
  b_orig = np.array([any(in_burst({1: H['u1'][e], 2: H['u2'][e]}, {1: H['t0_1'][e], 2: H['t0_2'][e]}, int(t) + 1).values()) for e, t in zip(ep, tt)])
  b_new = (np.array([any(in_burst({1: A['u1_new'][k], 2: A['u2_new'][k]}, {1: A['t0_1_new'][k], 2: A['t0_2_new'][k]}, int(tt[k]) + 1).values()) for k in range(len(tt))]) if A is not None else np.zeros(len(tt), bool))
  either = b_orig | b_new
  res_ii = {'n': int(len(dd)), 'maxdiff_all': q(dd), 'maxdiff_no_burst_either_context': q(dd[~either]), 'maxdiff_burst_in_either': q(dd[either]),
            'rows_exact_1e-5_no_burst': int((dd[~either] <= 1e-5).sum()), 'rows_exact_1e-5_burst': int((dd[either] <= 1e-5).sum()), 'burst_context_available': A is not None}
  MP.write_json(OUT / 'step.json', {'logged_one_step_replay': res_i, 'branch_first_row_vs_logged_next': res_ii, 'sample_rows': rows[:50]})
  print(json.dumps({'i': res_i, 'ii': res_ii}, indent=1), flush=True)


# ------------------------------------------------------------------ report
def mode_report(args):
  Hs = MP.read_json(OUT / 'hidden.json'); D = MP.read_json(OUT / 'diag.json'); Bj = MP.read_json(OUT / 'branch.json'); S = MP.read_json(OUT / 'step.json')
  ds = D['summary']
  L = ['# Step 0: same-context expert advice for the simulator-paired one-step ETT (AntMaze V6) -- what is reconstructable, what is not', '',
       'No training.  `hidden.json`, `diag.json`, `branch.json`, `step.json`; arrays `hidden.npz`, `teacher_state_at_anchors.npz`, `branch_advice.npz`.', '',
       '## 1. Hidden context and intent per d05 episode', '',
       f'd05 episodes per collection seed: {Hs["per_seed"]}.  Per-seed sidecars (U, t0, jitter, route coin, decisions, per-step holding) exist for seeds 606 / 610 / 611 only '
       f'({Hs["source_counts"]["sidecar"]} episodes); for 607-609 ({Hs["source_counts"]["regenerated"]} episodes) the collector\'s draws were regenerated by replaying its fixed-order RNG consumption.  '
       f'Validation of the regeneration on the available seeds (exact matches of 1,000): {json.dumps(Hs["regeneration_validation"])} -> exact: **{Hs["regeneration_exact_on_available_seeds"]}**.  '
       f'Intent (the coin) vs realised route in d05: equal in {Hs["intent_vs_realized_d05"]["equal"]} / {Hs["n"]} (detour intent {Hs["intent_vs_realized_d05"]["detour_intent"]}, realised {Hs["intent_vs_realized_d05"]["detour_realized"]}); the intent is taken from the coin, never from the label.', '',
       '## 2. Diagonal rows: the teacher replayed along the logged observations under the original timetable', '',
       f'Rows {ds["rows"]}: torque reproduced exactly in {ds["exact"]}, within 1e-5 in {ds["within_tol"]} (max |diff| {ds["maxdiff"]:.2e}); episodes fully exact {ds["episodes_all_exact"]} / {ds["n_episodes"]}.  '
       f'Per-step holding zone vs the sidecar record (seeds with sidecars): {ds["holding_zone_rows_agree"]} / {ds["holding_zone_rows_checked (sidecar seeds)"]} rows agree; final zone decisions agree in '
       f'{ds["decision_agree_sidecar"]["agree"]} / {ds["decision_agree_sidecar"]["n"]} episodes.  Teacher state snapshotted before {ds["anchors_snapshotted"]} anchor rows.', '',
       '## 3. Branch contexts: a_b under the redrawn timetable at every pilot anchor', '',
       f'Under the ORIGINAL timetable the reconstruction at the anchors gives a_b == a_q exactly in {Bj["original_timetable_reconstruction_exact"]} / {Bj["n"]} (within 1e-5: {Bj["original_within_tol"]}; max {Bj["original_maxdiff"]:.2e}).  '
       f'Under the branch\'s redrawn hidden context (the generator\'s own hazard seed; U1 / U2 matched the branch file for every anchor), with the zone latches re-derived by the teacher\'s rule at the recorded consultation steps: '
       f'classes {Bj["classes"]} (anchor-weighted {json.dumps({k: round(v, 4) for k, v in Bj["classes_weighted"].items()})}).  diagonal = same torque; off_hold = the teacher would hold (zero torque) while the query drives; '
       f'off_release = the teacher would drive while the logged torque is a hold; off_other = both drive but differ (median max|diff| {Bj["off_other_maxdiff_median"]}).', '',
       '| stratum | n | weight | diagonal | off_hold | off_release | off_other | holding (new) | holding (orig) | branch death share |', '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
  for name, b in Bj['by_stratum'].items():
    L.append(f'| {name} | {b["n"]} | {b["weight"]:.3f} | {b["diagonal"]:.3f} | {b["off_hold"]:.3f} | {b["off_release"]:.3f} | {b["off_other"]:.3f} | {b["holding_new"]:.3f} | {b["holding_orig"]:.3f} | {b["death_share_branch"]:.3f} |')
  L += ['', 'Death share of the branch by advice class: ' + ', '.join(f'{c}: {v["death_share"] if v["death_share"] is None else round(v["death_share"], 3)} (n {v["n"]})' for c, v in Bj['death_by_class'].items()), '',
        f'Onset labels: the d05 log has no failures (every episode reached the goal); deaths exist only in the branches ({Bj["onset_labels"]["branches_death"]} / {Bj["onset_labels"]["branches_total"]}).', '',
        '## 4. One-step determinism (hypothesis)', '']
  i, ii = S['logged_one_step_replay'], S['branch_first_row_vs_logged_next']
  L += [f'(i) Logged rows restored with the ORIGINAL context and stepped with the logged torque (n = {i["step_maxdiff_all"]["n"]}): restore max|diff| median {i["restore_maxdiff"]["median"]:.2e} / max {i["restore_maxdiff"]["max"]:.2e}; '
        f'next-state max|diff| outside rock bursts median {i["step_maxdiff_outside_bursts"]["median"]:.2e}, p99 {i["step_maxdiff_outside_bursts"]["p99"]:.2e}, max {i["step_maxdiff_outside_bursts"]["max"]:.2e} (exact <= 1e-5 in {i["rows_exact_1e-5_outside_bursts"]} / {i["step_maxdiff_outside_bursts"]["n"]}); '
        f'inside bursts median {i["step_maxdiff_inside_bursts"]["median"] if i["step_maxdiff_inside_bursts"]["median"] is None else format(i["step_maxdiff_inside_bursts"]["median"], ".2e")}, max {i["step_maxdiff_inside_bursts"]["max"]} (n {i["step_maxdiff_inside_bursts"]["n"]}; the rock geometry at t is not restored, so burst rows are not a determinism test).', '',
        f'(ii) The branches\' first post-query row vs the logged s_(t+1) -- same state, same torque, DIFFERENT hidden context (n = {ii["n"]}): outside bursts in either context median {ii["maxdiff_no_burst_either_context"]["median"]:.2e}, p99 {ii["maxdiff_no_burst_either_context"]["p99"]:.2e}, max {ii["maxdiff_no_burst_either_context"]["max"]:.2e} '
        f'(exact <= 1e-5 in {ii["rows_exact_1e-5_no_burst"]} / {ii["maxdiff_no_burst_either_context"]["n"]}); with a burst in either context median {ii["maxdiff_burst_in_either"]["median"]:.2e}, max {ii["maxdiff_burst_in_either"]["max"]:.2e} (n {ii["maxdiff_burst_in_either"]["n"]}).', '',
        '## 5. What can and cannot be established (written after the numbers)', '', '(filled in the SUMMARY by hand from the numbers above)']
  (OUT / 'REPORT.md').write_text('\n'.join(L) + '\n', encoding='utf-8')
  print('\n'.join(L), flush=True)


def main(argv=None):
  ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  ap.add_argument('mode', choices=('hidden', 'diag', 'branch', 'step', 'report'))
  args = ap.parse_args(argv)
  OUT.mkdir(parents=True, exist_ok=True)
  {'hidden': mode_hidden, 'diag': mode_diag, 'branch': mode_branch, 'step': mode_step, 'report': mode_report}[args.mode](args)
  return 0


if __name__ == '__main__':
  sys.exit(main())
