#!/usr/bin/env python
"""AntMaze V6 mainline with LEARNED-ETT futures (user's decision 2026-09-20), five paired seeds; the oracle arms extended to five.

The CF arm's branch table is regenerated by the learned one-step ETT instead of the simulator: from every anchor (the logged
row), the logged torque once, then the start agent's mode as the continuation -- the construction of the sealed simulator
branches (exp_v6_mainline_pilot._branch_one) with the simulator replaced by the model:
  motion / stationary gate / onset   the v3 one-step models (fit_v6_ett_one_step_v2 --v3), exact history counters
  advice a_b                          the advice generator v3 (fit_v6_ett_advice.py): state + own history (hold run, first mouth
                                      arrival) + ONE hidden context per path drawn from the prior and kept; MAP hold, sampled torque
  outcome                             the onset sampled step by step (one realised path per anchor, like one hazard draw); a path
                                      ends on its reach frame (|xy - goal| <= 0.5), its death frame, or the horizon 800 - t
  cross-fitting                       anchor k uses the models of ITS source-episode fold (never trained on its episode)
Nothing is read from the anchor's actual hidden context.  Oracle-supervised engineering stage: the ETT's supervision (advice,
onset labels, contexts, the context prior) came from the simulator; the futures used for training are the model's.

Arms (all the current mainline recipe = variant critic_clip0.1: start checkpoint, anchors, actor / BC rows, bc 0.05, critic clip
0.1, 30k updates): ETT (branches_ett.npz), CF (the sealed simulator branches), O (recorded).  Seeds 0..4; CF / O seeds 0-2 are the
existing clip finals, seeds 3-4 trained here.  Evaluation: a fresh paired draw (seed 8909, 300 episodes, policy mode) for all
fifteen finals and the start agent.  Rule (pre-registered): mean over the five paired seeds > 2 x seed s.e. and 5 / 5.

Round 3 of the CF-motion revision (user's plan after d8feadd): `--ett <name>` accepts any model dir ett_one_step_<name> on the v4
code path (the revised ETT `v4s20`: v4 + K 20 windows from the sealed table's start-agent branches), outputs under
ett_futures_<name>/; `--seeds 0 1 2` fixes the seed set before any result (three first, five if worth confirming); the second oracle
table's arm (oracle_draw2/CF, `CF2`) is reported next to the first as a reference so that no single oracle number is the yardstick.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'scripts'))

import exp_v6_mainline_pilot as MP  # noqa: E402
import fit_v6_ett_advice as FA  # noqa: E402
import fit_v6_ett_one_step_v2 as F2  # noqa: E402
from fit_v6_ett_one_step_v2 import in_band  # noqa: E402
from exp_v6_learned_ett import REGIONS, region_of  # noqa: E402

ETT = 'v3'                                             # --ett v4: the v4 one-step models (motion / stationary on (s, a_q) only); outputs under ett_futures_v4/
OUT = MP.OUT / 'ett_futures'
BRANCHES = OUT / 'branches_ett.npz'


def set_ett(version):
  """v3 / v4: the learned ETT of that version; 'hybrid': simulator motion + the v4 learned risk (exp_v6_hybrid_futures.py writes its branch table);
  any other name: the model dir ett_one_step_<name> on the v4 code path."""
  global ETT, OUT, BRANCHES
  ETT = version
  OUT = MP.OUT / ('ett_futures' if version == 'v3' else f'ett_futures_{version}')
  BRANCHES = OUT / 'branches_ett.npz'
  F2.OUT = F2.OUT_V4 if version in ('v4', 'hybrid') else (F2.OUT_V3 if version == 'v3' else MP.OUT / f'ett_one_step_{version}')
BASE_VARIANT = 'critic_clip0.1'
OVERRIDES = dict(MP.VARIANTS[BASE_VARIANT])
SEEDS = (0, 1, 2, 3, 4)
ARMS = ('ETT', 'CF', 'O')
REF_ARMS = ('CF2',)                                    # the second oracle table's arm (oracle_draw2/CF), reported as a reference
EVAL = {'n': 300, 'seed': 8909, 'policy': 'mean'}     # fresh draw (909 / 2909 / 3909 / 4909 / 6909 / 7909 used; 616_000_005 / 616_500_000 reserved)
GEN_SEED = 206_000_000
REACH_R = 0.5
STATE_DIM, OBS_W, ACTION_DIM, HORIZON = MP.STATE_DIM, MP.OBS_W, MP.ACTION_DIM, MP.HORIZON


def run_dir(arm, s):
  if arm == 'CF2':
    return MP.run_dir('CF', s, MP.OUT / 'oracle_draw2')
  return MP.run_dir('CF', s, OUT) if arm == 'ETT' else MP.run_dir(arm, s, MP.variant_base(BASE_VARIANT))


def eval_file(d):
  return d / f'eval_mean_s{EVAL["seed"]}.json'


# -------------------------------------------------------------------- seal
def mode_seal(args):
  OUT.mkdir(parents=True, exist_ok=True)
  p = OUT / 'manifest.json'
  if p.exists() and not args.force:
    print(f'{p} exists', flush=True); return
  man = {'experiment': 'AntMaze V6 mainline with learned-ETT futures (arm ETT) vs the sealed simulator futures (CF) and the recorded futures (O); five paired seeds',
         'sealed_at': time.strftime('%Y-%m-%d %H:%M:%S'), 'git_head': MP.git_head(), 'status': 'oracle-supervised engineering stage (the ETT was supervised by the simulator); the training futures of arm ETT are the model\'s',
         'ett': {'version': ETT, 'model_dir': str(F2.OUT), 'motion': ('the SIMULATOR with both rockfalls forced inactive (physics only; an oracle diagnostic control, not a learned method)' if ETT == 'hybrid' else 'learned (v4 motion regression + stationary gate on (s, a_q))' if ETT == 'v4' else 'learned (v3)' if ETT == 'v3' else f'learned ({ETT}: the v4 code path; see the model dir\'s json for the training recipe)'), 'motion_onset': {f'fold{f}': MP.sha256(F2.OUT / f'model_fold{f}.json') for f in range(FA.N_FOLDS)}, 'advice_generator': {f'fold{f}': MP.sha256(FA.OUT / f'gen3_fold{f}.json') for f in range(FA.N_FOLDS)},
                 'advice_gates': MP.read_json(FA.OUT / 'gates3_map.json'), 'rollout_check': ('ett_rollout_v3/hist_exact (variant B: pooled death 0.312 vs sim 0.294, KS death time 0.028)' if ETT in ('v3', 'v4', 'hybrid') else f'ett_rollout_v4/{ETT}/ (the Step 3a acceptance for this model dir)'),
                 'hold_decision': 'map', 'context_prior': FA.Z_PRIOR, 'history_counters': 'exact (run_length)', 'cross_fitting': 'anchor k uses the models of its source-episode fold (supervision.npz fold_anchor)'},
         'generation': {'construction': 'the logged torque once from the logged row, then the start agent mode (exp_v6_mainline_pilot.mode_policy) closed-loop through the model; one realised path per anchor; onset sampled per step; ends on reach / death / horizon 800 - t; no goal hold',
                        'seed': GEN_SEED, 'anchors': 'all 53,747 pilot anchors (anchors.npz)', 'query_coverage': 'logged torque only (as the sealed CF table)'},
         'arms': {'ETT': 'critic futures = branches_ett.npz', 'CF': 'critic futures = the sealed simulator branches (branches_cf.npz)', 'O': 'critic futures = the recorded continuation'},
         'recipe': {'variant': BASE_VARIANT, 'overrides': OVERRIDES, 'unchanged': ['start checkpoint', 'anchors', 'actor / BC rows (logged buffer)', 'bc 0.05', f'{MP.UPDATES} updates', 'stream seeds by seed']},
         'seeds': list(SEEDS), 'existing_finals': {f'{arm}/seed_{s}': (MP.sha256(run_dir(arm, s) / 'final.pkl') if (run_dir(arm, s) / 'final.pkl').exists() else 'to train') for arm in ('CF', 'O') + REF_ARMS for s in SEEDS},
         'reference_arms': {'CF2': 'oracle_draw2/CF -- the second simulator draw of the same protocol (reported next to CF; neither oracle number is the yardstick alone)'},
         'evaluation': {**EVAL, 'targets': 'ETT / CF / O seeds 0-4 and the start agent on the same 300 episodes'},
         'judgement': {'primary': 'ETT - O success on the common episodes, per paired seed: mean > 2 x seed s.e. and 5 / 5',
                       'oracle_reference': 'CF - O under the same rule at five seeds (the oracle gain re-established)',
                       'retention': '(ETT - O) / (CF - O) reported; ETT - CF reported (how much of the oracle gain the learned futures keep)',
                       'generation_check': 'branches_ett outcome shares vs the sealed simulator table, pooled and by anchor region (reported; a pooled death-share gap > 0.05 flags the futures)',
                       'no_selection': 'every final evaluated once; no tuning after the result'}}
  MP.write_json(p, man)
  print(json.dumps(man, indent=1), flush=True)


# ---------------------------------------------------------------- generate
def _policy_mode_batched():
  import jax
  import jax.numpy as jnp
  from crl import checkpoint
  cfg = MP.recipe_config(0, OUT / '_cfg'); MP.fill_dims(cfg); nets = MP.make_nets(cfg)
  _, st = checkpoint.load_checkpoint(MP.START_CKPT); pp = st.policy_params
  f = jax.jit(lambda o: jnp.tanh(nets.policy_network.apply(pp, o).loc))
  return lambda o31: np.asarray(f(jnp.asarray(o31, jnp.float32)), np.float32)


def generate_fold(fold, anchors, obs, act, ks, rng, mode):
  """All anchors of one fold, stepped together through the fold's models with fixed batch shapes.  Returns per-path rows."""
  n = len(ks); e, t = anchors.episode[ks].astype(np.int64), anchors.t[ks].astype(np.int64)
  P = F2.Predictor2(F2.load_model(fold)); gen = FA.load_generator(fold)
  goal = anchors.goal_xy[ks].astype(np.float32)
  s = anchors.state[ks].astype(np.float32)
  a0 = anchors.action[ks].astype(np.float32)
  z = FA.sample_context(rng, n)
  st = FA.PathState(FA.zero_run_before(act, e, t), np.where((t >= 1)[:, None], act[e, np.maximum(t - 1, 0)], 0.0).astype(np.float32),
                    np.stack([FA.first_mouth_in_prefix(obs[ee], int(tt)) for ee, tt in zip(e, t)]))
  max_steps = HORIZON - t
  alive = np.ones(n, bool); outcome = np.full(n, 'timeout', dtype='<U7'); L = np.ones(n, np.int64)
  step_rows = []                                          # (active idx, action taken from row j, next obs31)
  idx_all = np.arange(n)
  for j in range(int(max_steps.max())):
    active = alive & (j < max_steps)
    if not active.any():
      break
    o31 = np.concatenate([s, goal], axis=1)
    aq = a0 if j == 0 else mode(o31)
    t_abs = t + j
    band_now = in_band(s[:, :2].astype(np.float64))
    kb_now = st.band_counter(idx_all, j, band_now)
    m1, m2 = st.mouth_update(idx_all, t_abs, s[:, :2].astype(np.float64))
    ctx = FA.context_features(t_abs, *z); mf = FA.mouth_features(t_abs, m1, m2, z[2], z[3])
    x = FA.features(o31, ctx, mf, st.kh_prev, kb_now, st.prev_ab, gen.norm)
    hold, ab, _ = gen.sample(x, rng, decision='map')
    kh_now = st.hold_counter(idx_all, j, hold)
    s_next, p_on, _ = P.step(s, ab, aq, kh_now, kb_now)
    died = active & (rng.random(n) < p_on)
    reached = active & ~died & (np.linalg.norm(s_next[:, :2] - goal, axis=1) <= REACH_R)
    ia = np.flatnonzero(active)
    step_rows.append((ia, aq[ia].copy(), np.concatenate([s_next[ia], goal[ia]], axis=1).astype(np.float32)))
    L[ia] += 1
    outcome[died] = 'death'; outcome[reached] = 'success'; alive &= ~(died | reached)
    st.advance(idx_all, hold, ab)
    s = np.where(active[:, None], s_next, s).astype(np.float32)
  off = np.concatenate([[0], np.cumsum(L)[:-1]])
  R = int(L.sum())
  obs_rows = np.zeros((R, OBS_W), np.float32); act_rows = np.zeros((R, ACTION_DIM), np.float32)
  obs_rows[off] = anchors.obs31[ks].astype(np.float32)
  for j, (ia, aq, o_next) in enumerate(step_rows):
    act_rows[off[ia] + j] = aq; obs_rows[off[ia] + j + 1] = o_next
  return {'obs': obs_rows, 'act': act_rows, 'length': L, 'outcome': outcome, 'u1': z[0], 'u2': z[1], 't0_1': z[2], 't0_2': z[3], 'anchor_id': ks}


def mode_generate(args):
  if ETT == 'hybrid':
    raise SystemExit('the hybrid branch table is written by exp_v6_hybrid_futures.py generate')
  if BRANCHES.exists() and not args.force:
    print(f'{BRANCHES} exists', flush=True); return
  OUT.mkdir(parents=True, exist_ok=True)
  anchors, _ = MP.AnchorSet.load(MP.OUT / 'anchors.npz')
  obs, act, lengths, _ = MP.load_dataset()
  S = np.load(FA.EC / 'supervision.npz', allow_pickle=False); fold_anchor = S['fold_anchor'].astype(np.int64)
  mode = _policy_mode_batched()
  t0 = time.time(); parts = []
  for f in range(FA.N_FOLDS):
    ks = np.flatnonzero(fold_anchor == f)
    if args.limit:
      ks = ks[:int(args.limit)]
    rng = np.random.default_rng(GEN_SEED + f)
    parts.append(generate_fold(f, anchors, obs, act, ks, rng, mode))
    print(f'fold {f}: {len(ks)} paths, {time.time() - t0:.0f} s; outcome ' + json.dumps({k: round(float((parts[-1]["outcome"] == k).mean()), 3) for k in ("success", "death", "timeout")}), flush=True)
  order = np.argsort(np.concatenate([p['anchor_id'] for p in parts]))            # anchor order = the anchor set's
  cat = {k: np.concatenate([p[k] for p in parts]) for k in ('length', 'outcome', 'u1', 'u2', 't0_1', 't0_2', 'anchor_id')}
  obs_all = np.concatenate([p['obs'] for p in parts]); act_all = np.concatenate([p['act'] for p in parts])
  off_cat = np.concatenate([[0], np.cumsum(cat['length'])[:-1]])
  L = cat['length'][order]; off_new = np.concatenate([[0], np.cumsum(L)[:-1]])
  obs_rows = np.zeros_like(obs_all); act_rows = np.zeros_like(act_all)
  for i, o in enumerate(order):
    obs_rows[off_new[i]:off_new[i] + L[i]] = obs_all[off_cat[o]:off_cat[o] + L[i]]; act_rows[off_new[i]:off_new[i] + L[i]] = act_all[off_cat[o]:off_cat[o] + L[i]]
  ks = cat['anchor_id'][order]
  assert args.limit or np.array_equal(ks, np.arange(anchors.n))
  meta = {'source': f'learned ETT ({ETT} motion / onset + advice generator v3, MAP hold, prior context per path)', 'continuation_ckpt': str(MP.START_CKPT), 'continuation_ckpt_sha256': MP.sha256(MP.START_CKPT),
          'gen_seed': GEN_SEED, 'n_anchors': int(len(ks)), 'wall_seconds': time.time() - t0, 'outcome_counts': {k: int((cat['outcome'][order] == k).sum()) for k in ('success', 'death', 'timeout')},
          'hidden_context': 'sampled from the prior per path (u1 / u2 / t0 stored); the anchor\'s actual context is not read', 'filtering': 'none'}
  np.savez_compressed(BRANCHES, obs_rows=obs_rows, act_rows=act_rows, offset=off_new, length=L, episode=anchors.episode[ks], t=anchors.t[ks], outcome=cat['outcome'][order],
                      steps=(L - 1), u1=cat['u1'][order], u2=cat['u2'][order], t0_1=cat['t0_1'][order], t0_2=cat['t0_2'][order], n_query_steps=np.ones(len(ks), np.int64),
                      restore_maxdiff=np.zeros(len(ks), np.float32), hazard_seed=np.full(len(ks), GEN_SEED, np.int64), meta=np.asarray(json.dumps(meta, sort_keys=True)))
  summ = MP.generation_summary(BRANCHES, anchors)
  # vs the sealed simulator table, pooled and by anchor region
  with np.load(MP.OUT / 'branches_cf.npz', allow_pickle=False) as d:
    oc_cf, L_cf = d['outcome'].astype(str), d['length'].astype(np.int64)
  reg = region_of(anchors.state[ks, :2]); oc = cat['outcome'][order]; W = anchors.weight[ks]; oc_cf, L_cf = oc_cf[ks], L_cf[ks]
  cmp = {'pooled_weighted': {k: {'ett': float((W * (oc == k)).sum() / W.sum()), 'sim': float((W * (oc_cf == k)).sum() / W.sum())} for k in ('success', 'death', 'timeout')},
         'mean_rows': {'ett': float(L.mean()), 'sim': float(L_cf.mean())},
         'by_region': {REGIONS[i]: {'n': int((reg == i).sum()), **{k: {'ett': float((oc[reg == i] == k).mean()), 'sim': float((oc_cf[reg == i] == k).mean())} for k in ('success', 'death', 'timeout')}} for i in range(len(REGIONS)) if (reg == i).sum() >= 100}}
  MP.write_json(OUT / 'generation_ett.json', {'summary': summ, 'vs_simulator_table': cmp})
  print(json.dumps(cmp['pooled_weighted'], indent=1), flush=True)


# ------------------------------------------------------------------- train
def mode_train(args):
  if not (OUT / 'manifest.json').exists():
    raise SystemExit('seal first')
  s = int(args.seed)
  if args.arm == 'ETT':
    MP.train_arm('CF', s, base=OUT, branch_path=BRANCHES, overrides=OVERRIDES, inputs=MP.OUT)
  else:
    MP.train_arm(args.arm, s, base=MP.variant_base(BASE_VARIANT), overrides=OVERRIDES, inputs=MP.OUT)


# ---------------------------------------------------------------- evaluate
def mode_evaluate(args):
  MP.D.EVAL['seed'], MP.D.EVAL['n'] = EVAL['seed'], EVAL['n']
  todo = [(f'{arm}/seed_{s}', run_dir(arm, s) / 'final.pkl', run_dir(arm, s)) for arm in ARMS for s in SEEDS] + [('start', MP.START_CKPT, MP.OUT / 'start_agent')]
  for name, ck, od in todo:
    if args.only and name not in args.only:
      continue
    if not ck.exists():
      print(f'-- missing {name}: {ck}', flush=True); continue
    print(f'== evaluate {name}', flush=True)
    print(MP.D.evaluate_ckpt(ck, od, EVAL['policy']), flush=True)


# ------------------------------------------------------------------ report
def mode_report(args):
  man = MP.read_json(OUT / 'manifest.json')
  E = {arm: {s: MP._episodes(eval_file(run_dir(arm, s))) for s in SEEDS if eval_file(run_dir(arm, s)).exists()} for arm in ARMS + REF_ARMS}
  start = MP._episodes(eval_file(MP.OUT / 'start_agent')) if eval_file(MP.OUT / 'start_agent').exists() else None
  res = {'sealed_at': man['sealed_at'], 'eval': EVAL, 'headline': {arm: {s: MP._headline(e) for s, e in by.items()} for arm, by in E.items()}, 'paired': {}}
  if start is not None:
    res['headline']['start'] = MP._headline(start)
  full = [arm for arm in ARMS + REF_ARMS if len(E[arm]) == len(SEEDS)]
  for label, a, b in (('ETT - O', 'ETT', 'O'), ('CF - O', 'CF', 'O'), ('ETT - CF', 'ETT', 'CF'), ('CF2 - O', 'CF2', 'O'), ('ETT - CF2', 'ETT', 'CF2'), ('CF - CF2', 'CF', 'CF2')):
    if a in full and b in full:
      res['paired'][label] = {key: MP.paired_block(E[a], E[b], key=key) for key in ('success', 'detour', 'failure', 'timeout')}
  if start is not None:
    for a in full:
      res['paired'][f'{a} - start'] = {key: MP.paired_block(E[a], start, key=key) for key in ('success', 'detour', 'failure', 'timeout')}
  g = OUT / 'generation_ett.json'
  res['generation'] = MP.read_json(g) if g.exists() else None
  J = {'seeds': list(SEEDS), 'primary_ETT_minus_O': (res['paired'].get('ETT - O', {}).get('success', {}) or {}).get('improvement_rule_met'),
       'oracle_CF_minus_O': (res['paired'].get('CF - O', {}).get('success', {}) or {}).get('improvement_rule_met'),
       'oracle2_CF2_minus_O': (res['paired'].get('CF2 - O', {}).get('success', {}) or {}).get('improvement_rule_met')}
  if 'ETT - O' in res['paired'] and 'CF - O' in res['paired'] and res['paired']['CF - O']['success']['mean'] != 0:
    J['retention_of_oracle_gain'] = res['paired']['ETT - O']['success']['mean'] / res['paired']['CF - O']['success']['mean']
  if 'ETT - O' in res['paired'] and 'CF2 - O' in res['paired'] and res['paired']['CF2 - O']['success']['mean'] != 0:
    J['retention_of_oracle2_gain'] = res['paired']['ETT - O']['success']['mean'] / res['paired']['CF2 - O']['success']['mean']
  res['judgement'] = J
  MP.write_json(OUT / 'report.json', res)
  (OUT / 'REPORT.md').write_text(write_md(res, man), encoding='utf-8')
  print(json.dumps(J, indent=1), flush=True)


def write_md(res, man):
  L = [f'# Learned-ETT futures vs simulator futures vs recorded futures: {len(SEEDS)} paired seeds', '',
       f"Sealed {man['sealed_at']}.  Evaluation seed {res['eval']['seed']}, {res['eval']['n']} episodes, policy mode; the same episodes for every checkpoint.  Rule: mean over the {len(SEEDS)} paired seeds > 2 x seed s.e. and {len(SEEDS)} / {len(SEEDS)}.  CF2 = the second oracle table (oracle_draw2), a reference.", '',
       '## Headline (success / detour / death / timeout)', '', '| arm | ' + ' | '.join(f'seed {s}' for s in SEEDS) + ' | mean |', '|---|' + '---|' * (len(SEEDS) + 1)]
  for arm, by in res['headline'].items():
    if arm == 'start':
      h = by; L.append(f"| start | {h['success']:.3f} / {h['detour']:.2f} / {h['death']:.2f} / {h['timeout']:.2f} | " + ' | ' * (len(SEEDS) - 1) + ' |'); continue
    cells = [(f"{by[s]['success']:.3f} / {by[s]['detour']:.2f} / {by[s]['death']:.2f} / {by[s]['timeout']:.2f}" if s in by else '') for s in SEEDS]
    mean = np.mean([by[s]['success'] for s in by]) if by else float('nan')
    L.append(f'| {arm} | ' + ' | '.join(cells) + f' | {mean:.3f} |')
  L += ['', '## Paired differences (success)', '', '| comparison | ' + ' | '.join(f'seed {s}' for s in SEEDS) + ' | mean | seed s.e. | same direction | rule |', '|---|' + '---:|' * len(SEEDS) + '---:|---:|---:|---|']
  for label, blk in res['paired'].items():
    b = blk['success']
    L.append(f'| {label} | ' + ' | '.join((f"{b['per_seed'][s]['mean']:+.3f}" if s in b['per_seed'] else f"{b['per_seed'][str(s)]['mean']:+.3f}") for s in SEEDS) + f" | {b['mean']:+.3f} | {b['seed_se']:.3f} | {b['seeds_same_direction']} | {b['improvement_rule_met']} |")
  L += ['', '## Other keys (seed mean of the paired difference)', '', '| comparison | detour | death | timeout |', '|---|---:|---:|---:|']
  for label, blk in res['paired'].items():
    L.append(f"| {label} | {blk['detour']['mean']:+.3f} | {blk['failure']['mean']:+.3f} | {blk['timeout']['mean']:+.3f} |")
  g = res.get('generation')
  if g:
    c = g['vs_simulator_table']
    L += ['', '## The learned-ETT branch table vs the sealed simulator table (anchor-weighted outcome shares)', '', '| | success ETT / sim | death ETT / sim | timeout ETT / sim | mean rows ETT / sim |', '|---|---|---|---|---|',
          f"| pooled | {c['pooled_weighted']['success']['ett']:.3f} / {c['pooled_weighted']['success']['sim']:.3f} | {c['pooled_weighted']['death']['ett']:.3f} / {c['pooled_weighted']['death']['sim']:.3f} | {c['pooled_weighted']['timeout']['ett']:.3f} / {c['pooled_weighted']['timeout']['sim']:.3f} | {c['mean_rows']['ett']:.0f} / {c['mean_rows']['sim']:.0f} |"]
    for r, v in c['by_region'].items():
      L.append(f"| {r} (n {v['n']}) | {v['success']['ett']:.3f} / {v['success']['sim']:.3f} | {v['death']['ett']:.3f} / {v['death']['sim']:.3f} | {v['timeout']['ett']:.3f} / {v['timeout']['sim']:.3f} | |")
  L += ['', '## Judgement', '', '```', json.dumps(res['judgement'], indent=1), '```', '']
  return '\n'.join(L)


def main(argv=None):
  ap = argparse.ArgumentParser()
  ap.add_argument('mode', choices=('seal', 'generate', 'train', 'evaluate', 'report'))
  ap.add_argument('--arm', choices=ARMS, default='ETT')
  ap.add_argument('--seed', type=int, default=0)
  ap.add_argument('--only', nargs='*', default=None)
  ap.add_argument('--limit', type=int, default=None)
  ap.add_argument('--force', action='store_true')
  ap.add_argument('--ett', default='v3', help='v3 / v4 / hybrid, or any model dir name ett_one_step_<name> on the v4 code path (outputs ett_futures_<name>/)')
  ap.add_argument('--seeds', type=int, nargs='*', default=None, help='the seed set (default 0-4); fixed before any result')
  args = ap.parse_args(argv)
  global SEEDS
  if args.seeds:
    SEEDS = tuple(int(x) for x in args.seeds)
  set_ett(args.ett)
  {'seal': mode_seal, 'generate': mode_generate, 'train': mode_train, 'evaluate': mode_evaluate, 'report': mode_report}[args.mode](args)
  return 0


if __name__ == '__main__':
  sys.exit(main())
