"""Generate the four-arm launch scripts + experiment manifest.

Run AFTER the static worst-case table is built, so the real table SHA is baked
into every arm that consumes it. Arm A (historical k=3) is NOT generated: the
method could not be uniquely recovered from the repository -- see
artifacts/four_arm_wc_run/k3_recovery_report.md.

Usage:  python scripts/gen_four_arm_launchers.py
"""
import hashlib
import json
import os
import subprocess
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)

OUT = os.path.join(_ROOT, 'artifacts/four_arm_wc_run')
TABLE = 'artifacts/static_worstcase_rl/worstcase_table.npz'
CLEAN = ('artifacts/rockfall_v2_p30_h800_resetfix/failure_split/'
         'antmaze_rockfall_v2_p30_h800_resetfix_pilot_clean.npz')
CLEAN_SHA = '6bec8a52e771569c4edc14ff0c7319df4322fe6d74e6e69a6a7074fc76be1852'
BANK = 'artifacts/settled_failure_bank_alpha01/failure_bank_settled.npz'
BANK_SHA = '8c50202403317e8adc67670be716fffe5c3b3cb891017bfbe6eb070acd61d0ce'
V3 = 'artifacts/flow_v3_diverse_failure/flow_v3/flow_v3.pkl'
V3_SHA = '7b0ac9c80afa8713155d30ee4b784b52bd6d5b58fc57ff73b6b900a11224803c'
NORM = 'artifacts/flow_v0_clean/norm_stats.npz'
NORM_SHA = '262daa472316773b441e0dfed897275ffac13e10966728d39d4f9e23ffe8d4ca'
DPSI = 'artifacts/support_discriminator/D_state_cmdgoal_action'

STEPS, SEED, ALPHA, P_ACTIVE, HORIZON = 300000, 0, 0.1, 0.3, 800


def sha256_file(p):
  h = hashlib.sha256()
  with open(p, 'rb') as f:
    for b in iter(lambda: f.read(1 << 20), b''):
      h.update(b)
  return h.hexdigest()


def sha256_dir(p):
  """Stable digest over a model directory's files."""
  h = hashlib.sha256()
  for name in sorted(os.listdir(p)):
    fp = os.path.join(p, name)
    if os.path.isfile(fp):
      h.update(name.encode())
      h.update(sha256_file(fp).encode())
  return h.hexdigest()


HEADER = '''#!/usr/bin/env bash
# {title}
#
# {purpose}
#
# Generated by scripts/gen_four_arm_launchers.py -- do not hand-edit.
# Usage:  bash scripts/{fname} [--resume]
set -euo pipefail
cd "$(dirname "$0")/.."

ARM_NAME="{arm}"
RUN_ID="{run_id}"
SEED={seed}
STEPS={steps}
ALPHA={alpha}
P_ACTIVE={p_active}
HORIZON={horizon}
EXPECT_COMMIT="{commit}"
DIR="${{RUNS_ROOT:-.}}/$RUN_ID"

CLEAN_NPZ="{clean}"
CLEAN_SHA_PIN="{clean_sha}"
BANK_NPZ="{bank}"
BANK_SHA_PIN="{bank_sha}"
{extra_vars}
export PYTHONUNBUFFERED=1
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export MUJOCO_GL=${{MUJOCO_GL:-egl}}

sha_of () {{ python -c "import hashlib,sys;h=hashlib.sha256();f=open(sys.argv[1],'rb');[h.update(b) for b in iter(lambda:f.read(1<<20),b'')];print(h.hexdigest())" "$1"; }}

echo "======================================================================"
echo "ARM_NAME        : $ARM_NAME"
echo "RUN_ID          : $RUN_ID"
GIT_SHA=$(git rev-parse HEAD)
echo "GIT_SHA         : $GIT_SHA"
# A dirty tree is always fatal: the run must be reproducible from the commit.
if ! git diff --quiet HEAD -- crl scripts; then
  echo "ABORT: crl/ or scripts/ has uncommitted modifications" >&2
  exit 1
fi
# Commit pin. EXPECT_COMMIT is the commit this launcher was generated from; the
# launcher itself is committed AFTER generation, so HEAD is legitimately one
# commit ahead. Set STRICT_COMMIT=1 to force exact equality. The binding
# scientific guarantees are the CONTENT sha256 pins below (dataset, table,
# bank), which are commit-independent.
if [ "$GIT_SHA" != "$EXPECT_COMMIT" ]; then
  echo "NOTE: HEAD differs from the generation commit $EXPECT_COMMIT"
  if [ "${STRICT_COMMIT:-0}" = "1" ]; then
    echo "ABORT: STRICT_COMMIT=1 and commit mismatch" >&2; exit 1
  fi
fi
DATASET_SHA=$(sha_of "$CLEAN_NPZ")
echo "DATASET_SHA     : $DATASET_SHA"
[ "$DATASET_SHA" = "$CLEAN_SHA_PIN" ] || {{ echo "ABORT: dataset sha mismatch" >&2; exit 1; }}
echo "SEED            : $SEED"
echo "ALPHA_FAIL      : $ALPHA"
echo "PROPENSITY_TYPE : {prop_type}"
{extra_checks}
echo "GPU CHECK       :"
python -c "import jax;print('  backend',jax.default_backend());print('  devices',jax.devices());assert jax.default_backend()=='gpu' or __import__('os').environ.get('ALLOW_CPU')=='1', 'ABORT: no GPU (set ALLOW_CPU=1 only for a CPU smoke)'"
echo "STEPS           : $STEPS"
echo "OUTPUT DIR      : $DIR"
echo "======================================================================"

mkdir -p "$DIR"
python - <<PROV > "$DIR/arm_provenance.json"
import json, subprocess
print(json.dumps({prov_json}, indent=2))
PROV

python scripts/naive_rockfall_v2_crl.py \\
    --npz "$CLEAN_NPZ" \\
    --steps "$STEPS" --seed "$SEED" \\
    --ckpt-dir "$DIR" \\
    --p-active "$P_ACTIVE" --horizon "$HORIZON" --reset-fix \\
{train_args}    ${{1:-}} \\
    2>&1 | tee -a "$DIR/train.log"

# authoritative policy evaluation -- identical protocol/eval bank for all arms
for ckpt in final best; do
  python scripts/diagnose_naive_rockfall.py \\
      --v2 --p-active "$P_ACTIVE" --reset-fix --horizon "$HORIZON" \\
      --ckpt "$DIR/$ckpt.pkl" \\
      --out-dir "$DIR/eval_h800_resetfix/diag_$ckpt" \\
      2>&1 | tee -a "$DIR/diagnose.log"
done
echo "DONE $RUN_ID"
'''


def main():
  os.makedirs(OUT, exist_ok=True)
  table_sha = sha256_file(os.path.join(_ROOT, TABLE))
  dpsi_sha = sha256_dir(os.path.join(_ROOT, DPSI))
  commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'],
                                   cwd=_ROOT).decode().strip()
  with np.load(os.path.join(_ROOT, TABLE), allow_pickle=True) as t:
    n_rows = int(len(t['flat_index']))

  wc_vars = ('WC_TABLE="%s"\nWC_TABLE_SHA_PIN="%s"\n' % (TABLE, table_sha))
  wc_check = ('TABLE_SHA=$(sha_of "$WC_TABLE")\n'
              'echo "WC_TABLE_SHA    : $TABLE_SHA"\n'
              '[ "$TABLE_SHA" = "$WC_TABLE_SHA_PIN" ] || '
              '{ echo "ABORT: worst-case table sha mismatch -- arms must '
              'share ONE table" >&2; exit 1; }\n'
              'BANK_SHA=$(sha_of "$BANK_NPZ")\n'
              'echo "BANK_SHA        : $BANK_SHA"\n'
              '[ "$BANK_SHA" = "$BANK_SHA_PIN" ] || '
              '{ echo "ABORT: failure-bank sha mismatch" >&2; exit 1; }')

  arms = []

  # ---------------- Arm B: D_psi surrogate --------------------------------
  arms.append(dict(
      key='B', fname='run_wc_dpsi_surrogate_h800_a01_s0_300k.sh',
      run_id='wc_dpsi_surrogate_h800_a01_s0_300k',
      arm='Dpsi surrogate propensity ablation',
      title='Arm B -- D_psi SURROGATE propensity + worst-case branch',
      purpose=('APPROXIMATE PROPENSITY STRESS TEST. D_psi is a balanced '
               'behavior-vs-target SOURCE CLASSIFIER, NOT a calibrated causal '
               'propensity (see artifacts/static_worstcase_rl/'
               'g2_calibration_audit.json). Used frozen and raw, exactly as '
               'implemented: rho = sigmoid(logit), p_wc = 1 - rho. On the '
               'clean training transitions E[rho] ~ 0.505, so E[p_wc] ~ 0.495. '
               'This arm does NOT validate D_psi as a propensity estimator.'),
      prop_type='D_psi raw sigmoid SURROGATE (NOT calibrated; E[rho]~0.505)',
      alpha=ALPHA, wc=True,
      extra_vars=wc_vars + ('DPSI_MODEL="%s"\n' % DPSI),
      extra_checks=wc_check + '\necho "DPSI_MODEL      : $DPSI_MODEL"',
      train_args=('    --fail-bank "$BANK_NPZ" --fail-neg-alpha "$ALPHA" \\\n'
                  '    --arm-name "$ARM_NAME" \\\n'
                  '    --wc-positive --wc-table "$WC_TABLE" \\\n'
                  '    --wc-table-sha256 "$WC_TABLE_SHA_PIN" \\\n'
                  '    --wc-rho-mode dpsi --wc-dpsi-model "$DPSI_MODEL" \\\n'
                  '    --wc-coin-seed 0 \\\n'),
      propensity_type='dpsi_surrogate'))

  # ---------------- Arm C: fixed rate -------------------------------------
  arms.append(dict(
      key='C', fname='run_wc_fixedp10_h800_a01_s0_300k.sh',
      run_id='wc_fixedp10_h800_a01_s0_300k',
      arm='fixed-rate worst-case integration ablation',
      title='Arm C -- FIXED-RATE p_wc = 0.10 + worst-case branch',
      purpose=('Isolates whether the worst-case branch itself works, '
               'independently of propensity quality. p_wc = 0.10 has NO causal '
               'propensity interpretation whatsoever; it is a fixed rate. '
               'B ~ Bernoulli(rho = 0.90) for every transition.'),
      prop_type='fixed p_wc=0.10 (rho=0.90) -- NO causal interpretation',
      alpha=ALPHA, wc=True,
      extra_vars=wc_vars, extra_checks=wc_check,
      train_args=('    --fail-bank "$BANK_NPZ" --fail-neg-alpha "$ALPHA" \\\n'
                  '    --arm-name "$ARM_NAME" \\\n'
                  '    --wc-positive --wc-table "$WC_TABLE" \\\n'
                  '    --wc-table-sha256 "$WC_TABLE_SHA_PIN" \\\n'
                  '    --wc-rho-mode fixed --wc-p-wc 0.10 \\\n'
                  '    --wc-coin-seed 0 \\\n'),
      propensity_type='fixed_rate_0.10'))

  # ---------------- Arm D: pure blind -------------------------------------
  arms.append(dict(
      key='D', fname='run_blind_crl_h800_a00_s0_300k.sh',
      run_id='blind_crl_h800_a00_s0_300k',
      arm='pure blind CRL baseline',
      title='Arm D -- PURE BLIND CRL (alpha_fail = 0, no causal additions)',
      purpose=('Ordinary contrastive RL only: no propensity, no worst-case '
               'branch, no Flow, no selector, no static table, NO failure-'
               'negative augmentation (alpha_fail = 0). NOTE: this uses the '
               'CLEAN split so it is matched to arms B/C; the historical blind '
               'run naive_rockfall_v2_p30_h800_resetfix_s0_300k used the FULL '
               'pilot dataset (sha 08bdc44b...) and is therefore NOT '
               'dataset-matched -- see the runbook.'),
      prop_type='none (blind baseline)',
      alpha=0.0, wc=False, extra_vars='', extra_checks='',
      train_args='    --arm-name "$ARM_NAME" \\\n',
      propensity_type='none'))

  manifest = {'experiment': 'four-arm worst-case integration ablation',
              'scientific_status': ('MECHANISM / INTEGRATION ABLATIONS, not '
                                    'final causal-method validation. One seed '
                                    'is not statistical validation.'),
              'pinned_commit': commit,
              'shared': {
                  'dataset': CLEAN, 'dataset_sha256': CLEAN_SHA,
                  'environment': 'offline_ant_umaze_rockfall, p_active=0.30, '
                                 'H=800, reset_fix=True, severity v2.1',
                  'seed': SEED, 'steps': STEPS,
                  'batch_size': 1024, 'num_sgd_steps_per_step': 4,
                  'hidden': [1024, 1024], 'repr_dim': 16, 'twin_q': True,
                  'bc_coef': 0.05, 'random_goals': 0.0,
                  'entropy_coefficient': 0.0, 'lr': 3e-4,
                  'eval_every_steps': 10000, 'eval_episodes': 30,
                  'eval_protocol': ('scripts/diagnose_naive_rockfall.py --v2 '
                                    '--p-active 0.3 --reset-fix --horizon 800, '
                                    'n=200, FIXED eval seed bank (identical '
                                    'mask-pattern counts across arms)'),
                  'worstcase_table': TABLE, 'worstcase_table_sha256': table_sha,
                  'worstcase_table_rows': n_rows,
                  'flow_v3_sha256': V3_SHA, 'normalization_sha256': NORM_SHA,
                  'negative_bank_sha256': BANK_SHA, 'K': 256, 'ode_steps': 50,
                  'lambda': 0.01},
              'arms': {}, 'blocked_arms': {}, 'historical_references': {}}

  for a in arms:
    path = os.path.join(_ROOT, 'scripts', a['fname'])
    prov = ("{'arm_name': %r, 'run_id': %r, 'git_sha': subprocess."
            "check_output(['git','rev-parse','HEAD']).decode().strip(), "
            "'dataset': %r, 'dataset_sha256': %r, 'seed': %d, "
            "'alpha_fail': %s, 'worst_case_enabled': %s, "
            "'propensity_type': %r, 'steps': %d, 'table_sha256': %r}"
            % (a['arm'], a['run_id'], CLEAN, CLEAN_SHA, SEED, a['alpha'],
               a['wc'], a['propensity_type'], STEPS,
               table_sha if a['wc'] else None))
    body = HEADER.format(
        title=a['title'], purpose=a['purpose'], fname=a['fname'],
        arm=a['arm'], run_id=a['run_id'], seed=SEED, steps=STEPS,
        alpha=a['alpha'], p_active=P_ACTIVE, horizon=HORIZON, commit=commit,
        clean=CLEAN, clean_sha=CLEAN_SHA, bank=BANK, bank_sha=BANK_SHA,
        extra_vars=a['extra_vars'], extra_checks=a['extra_checks'],
        prop_type=a['prop_type'], train_args=a['train_args'], prov_json=prov)
    with open(path, 'w', newline='\n') as f:
      f.write(body)
    manifest['arms'][a['key']] = {
        'name': a['arm'], 'run_id': a['run_id'], 'script': 'scripts/' + a['fname'],
        'purpose': a['purpose'], 'git_sha': commit,
        'dataset_sha256': CLEAN_SHA, 'environment_H': HORIZON, 'seed': SEED,
        'alpha_fail': a['alpha'], 'worst_case_enabled': a['wc'],
        'propensity_type': a['propensity_type'],
        'rho_semantics': a['prop_type'],
        'flow_sha256': V3_SHA if a['wc'] else None,
        'worstcase_table_sha256': table_sha if a['wc'] else None,
        'negative_bank_sha256': BANK_SHA if a['alpha'] else None,
        'dpsi_sha256': dpsi_sha if a['propensity_type'] == 'dpsi_surrogate'
                       else None,
        'total_steps': STEPS,
        'output_dir': './' + a['run_id'],
        'log_path': 'logs/%s.log' % a['run_id'],
        'eval_dir': './%s/eval_h800_resetfix' % a['run_id']}
    print('wrote scripts/%s' % a['fname'])

  manifest['blocked_arms']['A'] = {
      'name': 'historical k=3 propensity + worst-case',
      'status': 'BLOCKED -- NOT PREPARED, NO SCRIPT GENERATED',
      'reason': ('the historical "k=3" propensity method could not be '
                 'uniquely recovered from the repository; see '
                 'artifacts/four_arm_wc_run/k3_recovery_report.md'),
      'instruction_followed': ('task: "If the exact historical k=3 method '
                               'cannot be uniquely recovered: STOP Arm A '
                               'preparation and report the ambiguity. Do not '
                               'invent a new k=3 estimator."')}

  manifest['historical_references']['fail_neg_only_alpha01'] = {
      'run': ('failneg_settledbank_a01_s0_300k/'
              'failneg_settledbank_p30_h800_resetfix_a01_s0_300k'),
      'role': 'historical comparison reference -- DO NOT RERUN',
      'dataset_sha256': CLEAN_SHA, 'alpha_fail': 0.1,
      'worst_case_enabled': False, 'propensity_type': 'none',
      'seed': SEED, 'steps': STEPS,
      'best': {'step': 208000, 'success': 0.66, 'hazard_exposure': 0.615,
               'drop_rate': 0.28, 'center_fraction': 0.34,
               'both_sides_success': 0.578},
      'protocol_match': ('same trainer, dataset, env, seed, budget and eval '
                         'protocol as arms B/C -- compatible, no rerun needed')}
  manifest['historical_references']['blind_crl_FULL_dataset'] = {
      'run': 'naive_rockfall_v2_p30_h800_resetfix_s0_300k',
      'role': ('historical blind baseline -- NOT dataset-matched (trained on '
               'the FULL pilot, sha 08bdc44b...). Arm D reruns the same '
               'configuration on the CLEAN split for a matched comparison.'),
      'dataset_sha256': ('08bdc44bb7942793ea18c2628c36d8ea8bfe875169afadfa89'
                         '34b1b948ef55e4'),
      'alpha_fail': 0.0,
      'final': {'step': 300000, 'success': 0.515, 'hazard_exposure': 0.98,
                'drop_rate': 0.45, 'center_fraction': 0.07,
                'both_sides_success': 0.20}}

  json.dump(manifest, open(os.path.join(OUT, 'experiment_manifest.json'), 'w'),
            indent=2)
  print('\ntable sha : %s  (%d rows)' % (table_sha, n_rows))
  print('commit    : %s' % commit)
  print('manifest  -> %s' % os.path.join(OUT, 'experiment_manifest.json'))


if __name__ == '__main__':
  main()
