"""Generate the four-arm launch scripts + experiment manifest.

Run AFTER the static worst-case table is built, so the real table SHA is baked
into every arm that consumes it.

The historical k=3 arm was DROPPED (it does not exist in this repository; see
artifacts/four_arm_wc_run/k3_recovery_report.md) and REPLACED by a second
fixed-rate arm at p_wc = 0.50. That is the scientifically load-bearing change:
p_wc = 0.50 is dose-matched to D_psi (whose empirical mean p_wc is ~0.495), so
the pair isolates whether D_psi contributes useful state/action dependence
BEYOND its mean branch rate.

Usage:  python scripts/gen_four_arm_launchers.py
"""
import hashlib
import json
import os
import subprocess
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
sys.path.insert(0, _ROOT)

OUT = os.path.join(_ROOT, 'artifacts/four_arm_wc_run')
TABLE = 'artifacts/static_worstcase_rl/worstcase_table.npz'
CLEAN = ('artifacts/rockfall_v2_p30_h800_resetfix/failure_split/'
         'antmaze_rockfall_v2_p30_h800_resetfix_pilot_clean.npz')
CLEAN_SHA = '6bec8a52e771569c4edc14ff0c7319df4322fe6d74e6e69a6a7074fc76be1852'
FULL_SHA = '08bdc44bb7942793ea18c2628c36d8ea8bfe875169afadfa8934b1b948ef55e4'
BANK = 'artifacts/settled_failure_bank_alpha01/failure_bank_settled.npz'
BANK_SHA = '8c50202403317e8adc67670be716fffe5c3b3cb891017bfbe6eb070acd61d0ce'
V3_SHA = '7b0ac9c80afa8713155d30ee4b784b52bd6d5b58fc57ff73b6b900a11224803c'
NORM_SHA = '262daa472316773b441e0dfed897275ffac13e10966728d39d4f9e23ffe8d4ca'
DPSI = 'artifacts/support_discriminator/D_state_cmdgoal_action'

STEPS, SEED, ALPHA, P_ACTIVE, HORIZON = 300000, 0, 0.1, 0.3, 800
BS = '\\'          # backslash for generated shell line-continuations


def sha256_file(p):
  h = hashlib.sha256()
  with open(p, 'rb') as f:
    for b in iter(lambda: f.read(1 << 20), b''):
      h.update(b)
  return h.hexdigest()


def sha256_dir(p):
  h = hashlib.sha256()
  for name in sorted(os.listdir(p)):
    fp = os.path.join(p, name)
    if os.path.isfile(fp):
      h.update(name.encode())
      h.update(sha256_file(fp).encode())
  return h.hexdigest()


HEADER = '''#!/usr/bin/env bash
# {title}
#
# {purpose}
#
# Generated by scripts/gen_four_arm_launchers.py -- do not hand-edit.
# Usage:  bash scripts/{fname} [--resume]
set -euo pipefail
cd "$(dirname "$0")/.."

ARM_NAME="{arm}"
RUN_ID="{run_id}"
SEED={seed}
STEPS={steps}
ALPHA={alpha}
P_ACTIVE={p_active}
HORIZON={horizon}
EXPECT_COMMIT="{commit}"
DIR="${{RUNS_ROOT:-.}}/$RUN_ID"

CLEAN_NPZ="{clean}"
CLEAN_SHA_PIN="{clean_sha}"
BANK_NPZ="{bank}"
BANK_SHA_PIN="{bank_sha}"
{extra_vars}
export PYTHONUNBUFFERED=1
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export MUJOCO_GL=${{MUJOCO_GL:-egl}}

sha_of () {{ python -c "import hashlib,sys;h=hashlib.sha256();f=open(sys.argv[1],'rb');[h.update(b) for b in iter(lambda:f.read(1<<20),b'')];print(h.hexdigest())" "$1"; }}

echo "======================================================================"
echo "ARM_NAME        : $ARM_NAME"
echo "RUN_ID          : $RUN_ID"
GIT_SHA=$(git rev-parse HEAD)
echo "GIT_SHA         : $GIT_SHA"
# A dirty tree is always fatal: the run must be reproducible from the commit.
if ! git diff --quiet HEAD -- crl scripts; then
  echo "ABORT: crl/ or scripts/ has uncommitted modifications" >&2
  exit 1
fi
# EXPECT_COMMIT is the commit these launchers were generated from; they are
# committed immediately after, so HEAD is legitimately one commit ahead.
# STRICT_COMMIT=1 forces exact equality. The binding scientific guarantees are
# the CONTENT sha256 pins below, which are commit-independent.
if [ "$GIT_SHA" != "$EXPECT_COMMIT" ]; then
  echo "NOTE: HEAD differs from the generation commit $EXPECT_COMMIT"
  if [ "${{STRICT_COMMIT:-0}}" = "1" ]; then
    echo "ABORT: STRICT_COMMIT=1 and commit mismatch" >&2; exit 1
  fi
fi
DATASET_SHA=$(sha_of "$CLEAN_NPZ")
echo "DATASET_SHA     : $DATASET_SHA"
[ "$DATASET_SHA" = "$CLEAN_SHA_PIN" ] || {{ echo "ABORT: dataset sha mismatch" >&2; exit 1; }}
echo "SEED            : $SEED"
echo "ALPHA_FAIL      : $ALPHA"
echo "PROPENSITY_TYPE : {prop_type}"
{extra_checks}
echo "GPU CHECK       :"
python -c "import jax,os;print('  backend',jax.default_backend());print('  devices',jax.devices());assert jax.default_backend()=='gpu' or os.environ.get('ALLOW_CPU')=='1', 'ABORT: no GPU (set ALLOW_CPU=1 only for a CPU smoke)'"
echo "STEPS           : $STEPS"
echo "OUTPUT DIR      : $DIR"
echo "======================================================================"

mkdir -p "$DIR"
python - <<PROV > "$DIR/arm_provenance.json"
import json, subprocess
print(json.dumps({prov_json}, indent=2))
PROV

python scripts/naive_rockfall_v2_crl.py {bs}
    --npz "$CLEAN_NPZ" {bs}
    --steps "$STEPS" --seed "$SEED" {bs}
    --ckpt-dir "$DIR" {bs}
    --p-active "$P_ACTIVE" --horizon "$HORIZON" --reset-fix {bs}
{train_args}    ${{1:-}} {bs}
    2>&1 | tee -a "$DIR/train.log"

# authoritative policy evaluation -- identical protocol / fixed eval seed bank
# for every arm. BOTH final and best are evaluated so arms are compared
# final-to-final and best-to-best.
for ckpt in final best; do
  python scripts/diagnose_naive_rockfall.py {bs}
      --v2 --p-active "$P_ACTIVE" --reset-fix --horizon "$HORIZON" {bs}
      --ckpt "$DIR/$ckpt.pkl" {bs}
      --out-dir "$DIR/eval_h800_resetfix/diag_$ckpt" {bs}
      2>&1 | tee -a "$DIR/diagnose.log"
done
echo "DONE $RUN_ID"
'''


def wc_train_args(mode_args):
  a = ('    --fail-bank "$BANK_NPZ" --fail-neg-alpha "$ALPHA" %s\n'
       '    --arm-name "$ARM_NAME" %s\n'
       '    --wc-positive --wc-table "$WC_TABLE" %s\n'
       '    --wc-table-sha256 "$WC_TABLE_SHA_PIN" %s\n' % (BS, BS, BS, BS))
  for line in mode_args:
    a += '    %s %s\n' % (line, BS)
  a += '    --wc-coin-seed 0 %s\n' % BS
  return a


def main():
  os.makedirs(OUT, exist_ok=True)
  table_sha = sha256_file(os.path.join(_ROOT, TABLE))
  dpsi_sha = sha256_dir(os.path.join(_ROOT, DPSI))
  commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'],
                                   cwd=_ROOT).decode().strip()
  with np.load(os.path.join(_ROOT, TABLE), allow_pickle=True) as t:
    n_rows = int(len(t['flat_index']))

  wc_vars = 'WC_TABLE="%s"\nWC_TABLE_SHA_PIN="%s"\n' % (TABLE, table_sha)
  wc_check = (
      'TABLE_SHA=$(sha_of "$WC_TABLE")\n'
      'echo "WC_TABLE_SHA    : $TABLE_SHA"\n'
      '[ "$TABLE_SHA" = "$WC_TABLE_SHA_PIN" ] || '
      '{ echo "ABORT: worst-case table sha mismatch -- all worst-case arms '
      'must share ONE table" >&2; exit 1; }\n'
      'BANK_SHA=$(sha_of "$BANK_NPZ")\n'
      'echo "BANK_SHA        : $BANK_SHA"\n'
      '[ "$BANK_SHA" = "$BANK_SHA_PIN" ] || '
      '{ echo "ABORT: failure-bank sha mismatch" >&2; exit 1; }')

  arms = [
      dict(key='S1', fname='run_wc_fixedp10_h800_a01_s0_300k.sh',
           run_id='wc_fixedp10_h800_a01_s0_300k',
           arm='fixed-rate worst-case integration ablation (p_wc=0.10)',
           title='Server 1 -- FIXED-RATE p_wc = 0.10 + worst-case branch',
           purpose=('Low-dose fixed-rate arm. Isolates whether the worst-case '
                    'branch itself works, independently of propensity '
                    'quality. p_wc = 0.10 has NO causal propensity '
                    'interpretation; B ~ Bernoulli(rho = 0.90) for every '
                    'transition.'),
           prop_type='fixed p_wc=0.10 (rho=0.90) -- NO causal interpretation',
           alpha=ALPHA, wc=True, extra_vars=wc_vars, extra_checks=wc_check,
           train_args=wc_train_args(['--wc-rho-mode fixed --wc-p-wc 0.10']),
           propensity_type='fixed_rate_0.10'),
      dict(key='S2', fname='run_wc_fixedp50_h800_a01_s0_300k.sh',
           run_id='wc_fixedp50_h800_a01_s0_300k',
           arm='fixed-rate worst-case integration ablation (p_wc=0.50)',
           title='Server 2 -- FIXED-RATE p_wc = 0.50 (DOSE-MATCHED to D_psi)',
           purpose=('DOSE-MATCHED CONTROL FOR D_psi, and the replacement for '
                    'the dropped k=3 arm. p_wc = 0.50 has NO causal propensity '
                    'interpretation; it is a fixed rate chosen to match the '
                    'empirical mean branch rate of D_psi (~0.495). Comparing '
                    'this arm against the D_psi arm isolates whether D_psi '
                    'contributes useful STATE/ACTION DEPENDENCE beyond its '
                    'mean dose: same average worst-case exposure, one '
                    'state-dependent and one not.'),
           prop_type=('fixed p_wc=0.50 (rho=0.50) -- dose-matched control, NO '
                      'causal interpretation'),
           alpha=ALPHA, wc=True, extra_vars=wc_vars, extra_checks=wc_check,
           train_args=wc_train_args(['--wc-rho-mode fixed --wc-p-wc 0.50']),
           propensity_type='fixed_rate_0.50'),
      dict(key='S3', fname='run_wc_dpsi_surrogate_h800_a01_s0_300k.sh',
           run_id='wc_dpsi_surrogate_h800_a01_s0_300k',
           arm='Dpsi surrogate propensity ablation',
           title='Server 3 -- D_psi SURROGATE propensity + worst-case branch',
           purpose=('APPROXIMATE PROPENSITY STRESS TEST. D_psi is a balanced '
                    'behavior-vs-target SOURCE CLASSIFIER, NOT a calibrated '
                    'causal propensity (see artifacts/static_worstcase_rl/'
                    'g2_calibration_audit.json). Used frozen and raw, exactly '
                    'as implemented: rho = sigmoid(logit), p_wc = 1 - rho. On '
                    'the clean training transitions E[rho] ~ 0.505, so '
                    'E[p_wc] ~ 0.495 -- but the realized rate is NOT forced. '
                    'This arm does NOT validate D_psi as a propensity '
                    'estimator.'),
           prop_type=('D_psi raw sigmoid SURROGATE -- NOT a calibrated '
                      'propensity (expected E[rho]~0.505, not forced)'),
           alpha=ALPHA, wc=True,
           extra_vars=wc_vars + 'DPSI_MODEL="%s"\n' % DPSI,
           extra_checks=wc_check + '\necho "DPSI_MODEL      : $DPSI_MODEL"',
           train_args=wc_train_args(
               ['--wc-rho-mode dpsi --wc-dpsi-model "$DPSI_MODEL"']),
           propensity_type='dpsi_surrogate'),
      dict(key='S4', fname='run_blind_crl_clean_h800_a00_s0_300k.sh',
           run_id='blind_crl_clean_h800_a00_s0_300k',
           arm='pure blind CRL baseline (clean dataset)',
           title='Server 4 -- PURE BLIND CRL (alpha_fail = 0, clean dataset)',
           purpose=('Ordinary contrastive RL only: no propensity, no '
                    'worst-case branch, no Flow, no similarity selector, no '
                    'static table, NO failure-negative augmentation '
                    '(alpha_fail = 0). Uses the CLEAN split so it is '
                    'dataset-matched to the three worst-case arms and to the '
                    'historical fail-neg-only reference. The historical blind '
                    'run naive_rockfall_v2_p30_h800_resetfix_s0_300k used the '
                    'FULL pilot (sha 08bdc44b...) and is kept only as a '
                    'secondary, NOT dataset-matched reference.'),
           prop_type='none (blind baseline)',
           alpha=0.0, wc=False, extra_vars='', extra_checks='',
           train_args='    --arm-name "$ARM_NAME" %s\n' % BS,
           propensity_type='none'),
  ]

  manifest = {
      'experiment': 'four-arm worst-case integration ablation',
      'scientific_status': ('MECHANISM / INTEGRATION ABLATIONS, not final '
                            'causal-method validation. Arm S3 does NOT '
                            'validate D_psi as a propensity; arms S1/S2 have '
                            'no causal propensity interpretation; one seed is '
                            'not statistical validation.'),
      'pinned_commit': commit,
      'shared': {
          'dataset': CLEAN, 'dataset_sha256': CLEAN_SHA,
          'environment': ('offline_ant_umaze_rockfall, p_active=0.30, H=800, '
                          'reset_fix=True, severity v2.1 (0.80/0.15/0.05)'),
          'seed': SEED, 'steps': STEPS, 'batch_size': 1024,
          'num_sgd_steps_per_step': 4, 'hidden': [1024, 1024], 'repr_dim': 16,
          'twin_q': True, 'bc_coef': 0.05, 'random_goals': 0.0,
          'entropy_coefficient': 0.0, 'lr': 3e-4, 'discount': 0.99,
          'eval_every_steps': 10000, 'eval_episodes': 30,
          'eval_protocol': ('scripts/diagnose_naive_rockfall.py --v2 '
                            '--p-active 0.3 --reset-fix --horizon 800, n=200, '
                            'FIXED eval seed bank (identical mask-pattern '
                            'counts 48/45/53/54 across all runs)'),
          'worstcase_table': TABLE, 'worstcase_table_sha256': table_sha,
          'worstcase_table_rows': n_rows,
          'flow_v3_sha256': V3_SHA, 'normalization_sha256': NORM_SHA,
          'negative_bank_sha256': BANK_SHA,
          'K': 256, 'ode_steps': 50, 'lambda': 0.01,
          'selector': ('argmin_k min_g ||norm(s_k) - norm(g)||_2 over the '
                       '16-state bank; lowest-index tie-break; no Critic C')},
      'arms': {}, 'dropped_arms': {}, 'historical_references': {}}

  for a in arms:
    prov = ("{'arm_name': %r, 'run_id': %r, 'git_sha': subprocess."
            "check_output(['git','rev-parse','HEAD']).decode().strip(), "
            "'dataset': %r, 'dataset_sha256': %r, 'seed': %d, "
            "'alpha_fail': %s, 'worst_case_enabled': %s, "
            "'propensity_type': %r, 'steps': %d, 'table_sha256': %r}"
            % (a['arm'], a['run_id'], CLEAN, CLEAN_SHA, SEED, a['alpha'],
               a['wc'], a['propensity_type'], STEPS,
               table_sha if a['wc'] else None))
    body = HEADER.format(
        title=a['title'], purpose=a['purpose'], fname=a['fname'],
        arm=a['arm'], run_id=a['run_id'], seed=SEED, steps=STEPS,
        alpha=a['alpha'], p_active=P_ACTIVE, horizon=HORIZON, commit=commit,
        clean=CLEAN, clean_sha=CLEAN_SHA, bank=BANK, bank_sha=BANK_SHA,
        extra_vars=a['extra_vars'], extra_checks=a['extra_checks'],
        prop_type=a['prop_type'], train_args=a['train_args'],
        prov_json=prov, bs=BS)
    with open(os.path.join(_ROOT, 'scripts', a['fname']), 'w',
              newline='\n') as f:
      f.write(body)
    manifest['arms'][a['key']] = {
        'name': a['arm'], 'run_id': a['run_id'],
        'script': 'scripts/' + a['fname'], 'purpose': a['purpose'],
        'git_sha': commit, 'dataset': CLEAN, 'dataset_sha256': CLEAN_SHA,
        'environment_H': HORIZON, 'seed': SEED, 'alpha_fail': a['alpha'],
        'worst_case_enabled': a['wc'],
        'propensity_type': a['propensity_type'],
        'rho_semantics': a['prop_type'],
        'flow_sha256': V3_SHA if a['wc'] else None,
        'worstcase_table_sha256': table_sha if a['wc'] else None,
        'negative_bank_sha256': BANK_SHA if a['alpha'] else None,
        'dpsi_sha256': (dpsi_sha if a['propensity_type'] == 'dpsi_surrogate'
                        else None),
        'total_steps': STEPS, 'output_dir': './' + a['run_id'],
        'log_path': 'logs/%s.log' % a['run_id'],
        'eval_dir': './%s/eval_h800_resetfix' % a['run_id']}
    print('wrote scripts/%s' % a['fname'])

  manifest['dropped_arms']['historical_k3'] = {
      'name': 'historical k=3 propensity + worst-case',
      'status': ('DROPPED by the user after recovery failed; REPLACED by '
                 'wc_fixedp50_h800_a01_s0_300k'),
      'reason': ('no historical k=3 propensity exists anywhere in the '
                 'repository, on any branch, or in git history; see '
                 'artifacts/four_arm_wc_run/k3_recovery_report.md'),
      'not_invented': True}

  manifest['key_matched_comparison'] = {
      'pair': ['wc_fixedp50_h800_a01_s0_300k',
               'wc_dpsi_surrogate_h800_a01_s0_300k'],
      'rationale': ('approximately equal AVERAGE worst-case dose (fixed 0.500 '
                    'vs D_psi empirical mean ~0.495). The only difference is '
                    'that D_psi varies with (s, g_cmd, a) while the fixed arm '
                    'does not, so the contrast isolates whether D_psi '
                    'contributes useful state/action dependence BEYOND its '
                    'mean branch rate.'),
      'dose_check': ('confirm the realized worst-case rates in the smoke logs '
                     'before launch; do NOT force D_psi to match 0.50')}

  manifest['historical_references']['fail_neg_only_alpha01_CLEAN'] = {
      'run': ('failneg_settledbank_a01_s0_300k/'
              'failneg_settledbank_p30_h800_resetfix_a01_s0_300k'),
      'role': 'PRIMARY historical comparison reference -- DO NOT RERUN',
      'dataset_sha256': CLEAN_SHA, 'alpha_fail': 0.1,
      'worst_case_enabled': False, 'propensity_type': 'none',
      'seed': SEED, 'steps': STEPS,
      'final': {'step': 300000, 'success': 0.645, 'hazard_exposure': 0.770,
                'drop_rate': 0.335, 'center_fraction': 0.260,
                'both_sides_success': 0.400, 'left_only_success': 0.943,
                'right_only_success': 0.315, 'trigger_avoidance': 0.060},
      'best': {'step': 208000, 'success': 0.660, 'hazard_exposure': 0.615,
               'drop_rate': 0.280, 'center_fraction': 0.340,
               'both_sides_success': 0.578, 'left_only_success': 0.887,
               'right_only_success': 0.315, 'trigger_avoidance': 0.036},
      'protocol_match': ('same trainer, dataset, env, seed, budget and eval '
                         'protocol as the worst-case arms -- compatible, no '
                         'rerun needed'),
      'reporting_rule': ('BOTH final and best recorded; compare every new arm '
                         'final-to-final and best-to-best. NEVER compare this '
                         'best against a new-run final.')}
  manifest['historical_references']['blind_crl_FULL_dataset'] = {
      'run': 'naive_rockfall_v2_p30_h800_resetfix_s0_300k',
      'role': ('SECONDARY reference only -- NOT dataset-matched (FULL pilot, '
               'sha 08bdc44b...). The dataset-matched blind baseline is the '
               'new arm blind_crl_clean_h800_a00_s0_300k.'),
      'dataset_sha256': FULL_SHA, 'alpha_fail': 0.0,
      'final': {'step': 300000, 'success': 0.515, 'hazard_exposure': 0.980,
                'drop_rate': 0.450, 'center_fraction': 0.070,
                'both_sides_success': 0.200, 'left_only_success': 0.906,
                'right_only_success': 0.093, 'trigger_avoidance': 0.031},
      'best': {'step': 239200, 'success': 0.520, 'hazard_exposure': 0.920,
               'drop_rate': 0.430, 'center_fraction': 0.110,
               'both_sides_success': 0.178, 'left_only_success': 0.925,
               'right_only_success': 0.111, 'trigger_avoidance': 0.046}}
  manifest['reporting_rule'] = (
      'Report final AND best for every arm from the identical eval protocol '
      '(n=200, fixed eval seed bank). Compare like with like: final-to-final '
      'and best-to-best.')

  json.dump(manifest, open(os.path.join(OUT, 'experiment_manifest.json'), 'w'),
            indent=2)
  print('\ntable sha : %s  (%d rows)' % (table_sha, n_rows))
  print('D_psi sha : %s' % dpsi_sha)
  print('commit    : %s' % commit)
  print('manifest  -> %s' % os.path.join(OUT, 'experiment_manifest.json'))


if __name__ == '__main__':
  main()
