#!/usr/bin/env bash
# Server 3 -- D_psi SURROGATE propensity + worst-case branch
#
# APPROXIMATE PROPENSITY STRESS TEST. D_psi is a balanced behavior-vs-target SOURCE CLASSIFIER, NOT a calibrated causal propensity (see artifacts/static_worstcase_rl/g2_calibration_audit.json). Used frozen and raw, exactly as implemented: rho = sigmoid(logit), p_wc = 1 - rho. On the clean training transitions E[rho] ~ 0.505, so E[p_wc] ~ 0.495 -- but the realized rate is NOT forced. This arm does NOT validate D_psi as a propensity estimator.
#
# Generated by scripts/gen_four_arm_launchers.py -- do not hand-edit.
# Usage:  bash scripts/run_wc_dpsi_surrogate_h800_a01_s0_300k.sh [--resume]
set -euo pipefail
cd "$(dirname "$0")/.."

ARM_NAME="Dpsi surrogate propensity ablation"
RUN_ID="wc_dpsi_surrogate_h800_a01_s0_300k"
SEED=0
STEPS=300000
ALPHA=0.1
P_ACTIVE=0.3
HORIZON=800
EXPECT_COMMIT="e7341aa2312decb3ed667877eab1f602c62a04c3"
DIR="${RUNS_ROOT:-.}/$RUN_ID"

CLEAN_NPZ="artifacts/rockfall_v2_p30_h800_resetfix/failure_split/antmaze_rockfall_v2_p30_h800_resetfix_pilot_clean.npz"
CLEAN_SHA_PIN="6bec8a52e771569c4edc14ff0c7319df4322fe6d74e6e69a6a7074fc76be1852"
BANK_NPZ="artifacts/settled_failure_bank_alpha01/failure_bank_settled.npz"
BANK_SHA_PIN="8c50202403317e8adc67670be716fffe5c3b3cb891017bfbe6eb070acd61d0ce"
WC_TABLE="artifacts/static_worstcase_rl/worstcase_table.npz"
WC_TABLE_SHA_PIN="d059db0cdae4cd528cdb68e6c0caf7439cc5d66429a39b7b883ecf15d974ac4b"
DPSI_MODEL="artifacts/support_discriminator/D_state_cmdgoal_action"

export PYTHONUNBUFFERED=1
export XLA_PYTHON_CLIENT_PREALLOCATE=false
export MUJOCO_GL=${MUJOCO_GL:-egl}

sha_of () { python -c "import hashlib,sys;h=hashlib.sha256();f=open(sys.argv[1],'rb');[h.update(b) for b in iter(lambda:f.read(1<<20),b'')];print(h.hexdigest())" "$1"; }

echo "======================================================================"
echo "ARM_NAME        : $ARM_NAME"
echo "RUN_ID          : $RUN_ID"
GIT_SHA=$(git rev-parse HEAD)
echo "GIT_SHA         : $GIT_SHA"
# A dirty tree is always fatal: the run must be reproducible from the commit.
if ! git diff --quiet HEAD -- crl scripts; then
  echo "ABORT: crl/ or scripts/ has uncommitted modifications" >&2
  exit 1
fi
# EXPECT_COMMIT is the commit these launchers were generated from; they are
# committed immediately after, so HEAD is legitimately one commit ahead.
# STRICT_COMMIT=1 forces exact equality. The binding scientific guarantees are
# the CONTENT sha256 pins below, which are commit-independent.
if [ "$GIT_SHA" != "$EXPECT_COMMIT" ]; then
  echo "NOTE: HEAD differs from the generation commit $EXPECT_COMMIT"
  if [ "${STRICT_COMMIT:-0}" = "1" ]; then
    echo "ABORT: STRICT_COMMIT=1 and commit mismatch" >&2; exit 1
  fi
fi
DATASET_SHA=$(sha_of "$CLEAN_NPZ")
echo "DATASET_SHA     : $DATASET_SHA"
[ "$DATASET_SHA" = "$CLEAN_SHA_PIN" ] || { echo "ABORT: dataset sha mismatch" >&2; exit 1; }
echo "SEED            : $SEED"
echo "ALPHA_FAIL      : $ALPHA"
echo "PROPENSITY_TYPE : D_psi raw sigmoid SURROGATE -- NOT a calibrated propensity (expected E[rho]~0.505, not forced)"
TABLE_SHA=$(sha_of "$WC_TABLE")
echo "WC_TABLE_SHA    : $TABLE_SHA"
[ "$TABLE_SHA" = "$WC_TABLE_SHA_PIN" ] || { echo "ABORT: worst-case table sha mismatch -- all worst-case arms must share ONE table" >&2; exit 1; }
BANK_SHA=$(sha_of "$BANK_NPZ")
echo "BANK_SHA        : $BANK_SHA"
[ "$BANK_SHA" = "$BANK_SHA_PIN" ] || { echo "ABORT: failure-bank sha mismatch" >&2; exit 1; }
echo "DPSI_MODEL      : $DPSI_MODEL"
echo "GPU CHECK       :"
python -c "import jax,os;print('  backend',jax.default_backend());print('  devices',jax.devices());assert jax.default_backend()=='gpu' or os.environ.get('ALLOW_CPU')=='1', 'ABORT: no GPU (set ALLOW_CPU=1 only for a CPU smoke)'"
echo "STEPS           : $STEPS"
echo "OUTPUT DIR      : $DIR"
echo "======================================================================"

mkdir -p "$DIR"
python - <<PROV > "$DIR/arm_provenance.json"
import json, subprocess
print(json.dumps({'arm_name': 'Dpsi surrogate propensity ablation', 'run_id': 'wc_dpsi_surrogate_h800_a01_s0_300k', 'git_sha': subprocess.check_output(['git','rev-parse','HEAD']).decode().strip(), 'dataset': 'artifacts/rockfall_v2_p30_h800_resetfix/failure_split/antmaze_rockfall_v2_p30_h800_resetfix_pilot_clean.npz', 'dataset_sha256': '6bec8a52e771569c4edc14ff0c7319df4322fe6d74e6e69a6a7074fc76be1852', 'seed': 0, 'alpha_fail': 0.1, 'worst_case_enabled': True, 'propensity_type': 'dpsi_surrogate', 'steps': 300000, 'table_sha256': 'd059db0cdae4cd528cdb68e6c0caf7439cc5d66429a39b7b883ecf15d974ac4b'}, indent=2))
PROV

python scripts/naive_rockfall_v2_crl.py \
    --npz "$CLEAN_NPZ" \
    --steps "$STEPS" --seed "$SEED" \
    --ckpt-dir "$DIR" \
    --p-active "$P_ACTIVE" --horizon "$HORIZON" --reset-fix \
    --fail-bank "$BANK_NPZ" --fail-neg-alpha "$ALPHA" \
    --arm-name "$ARM_NAME" \
    --wc-positive --wc-table "$WC_TABLE" \
    --wc-table-sha256 "$WC_TABLE_SHA_PIN" \
    --wc-rho-mode dpsi --wc-dpsi-model "$DPSI_MODEL" \
    --wc-coin-seed 0 \
    ${1:-} \
    2>&1 | tee -a "$DIR/train.log"

# authoritative policy evaluation -- identical protocol / fixed eval seed bank
# for every arm. BOTH final and best are evaluated so arms are compared
# final-to-final and best-to-best.
for ckpt in final best; do
  python scripts/diagnose_naive_rockfall.py \
      --v2 --p-active "$P_ACTIVE" --reset-fix --horizon "$HORIZON" \
      --ckpt "$DIR/$ckpt.pkl" \
      --out-dir "$DIR/eval_h800_resetfix/diag_$ckpt" \
      2>&1 | tee -a "$DIR/diagnose.log"
done
echo "DONE $RUN_ID"
